from decimal import Decimal

from django.db import transaction as db_transaction
from django.utils import timezone

from .accounting_controls import ensure_period_is_open
from .models import (
    Bill,
    ChartOfAccounts,
    Customer,
    GeneralLedger,
    IntercompanyEliminationEntry,
    IntercompanyTransaction,
    Invoice,
    JournalEntry,
    Loan,
    Vendor,
)


DECIMAL_ZERO = Decimal('0.00')


def _make_reference(prefix, base_reference):
    return f'{prefix}-{base_reference}'[:50]


def _signed_amount(account_type, debit_amount, credit_amount):
    debit_amount = Decimal(str(debit_amount or 0))
    credit_amount = Decimal(str(credit_amount or 0))
    if account_type in {'asset', 'expense'}:
        return debit_amount - credit_amount
    return credit_amount - debit_amount


def _account_code(prefix, counterparty_id):
    return f'{prefix}{counterparty_id:04d}'[:20]


def _find_or_create_account(entity, code, name, account_type):
    account, _ = ChartOfAccounts.objects.get_or_create(
        entity=entity,
        account_code=code,
        defaults={
            'account_name': name,
            'account_type': account_type,
            'currency': entity.local_currency,
            'status': 'active',
        },
    )
    return account


def _ensure_internal_customer(entity, counterparty):
    customer_code = f'IC-CUS-{entity.id}-{counterparty.id}'[:50]
    customer, _ = Customer.objects.get_or_create(
        entity=entity,
        customer_code=customer_code,
        defaults={
            'customer_name': f'{counterparty.name} (Intercompany)',
            'email': f'intercompany+entity{counterparty.id}@internal.atonixcorp',
            'address': counterparty.country,
            'city': counterparty.country,
            'country': counterparty.country,
            'postal_code': '00000',
            'contact_person': 'Intercompany Settlement',
            'currency': entity.local_currency,
            'status': 'active',
        },
    )
    return customer


def _ensure_internal_vendor(entity, counterparty):
    vendor_code = f'IC-VEN-{entity.id}-{counterparty.id}'[:50]
    vendor, _ = Vendor.objects.get_or_create(
        entity=entity,
        vendor_code=vendor_code,
        defaults={
            'vendor_name': f'{counterparty.name} (Intercompany)',
            'email': f'intercompany+entity{counterparty.id}@internal.atonixcorp',
            'address': counterparty.country,
            'city': counterparty.country,
            'country': counterparty.country,
            'postal_code': '00000',
            'contact_person': 'Intercompany Settlement',
            'currency': entity.local_currency,
            'status': 'active',
        },
    )
    return vendor


def _create_journal_entry(entity, reference_number, description, posting_date, created_by, debit_account, credit_account, amount):
    amount = Decimal(str(amount or 0)).quantize(Decimal('0.01'))
    journal_entry = JournalEntry.objects.create(
        entity=entity,
        entry_type='automated',
        reference_number=reference_number,
        description=description,
        posting_date=posting_date,
        memo='Automatically generated by the intercompany engine.',
        amount_total=amount,
        status='posted',
        created_by=created_by,
        approved_by=created_by,
        approved_at=timezone.now(),
        submitted_at=timezone.now(),
    )
    GeneralLedger.objects.create(
        entity=entity,
        debit_account=debit_account,
        credit_account=credit_account,
        debit_amount=amount,
        credit_amount=amount,
        description=description,
        reference_number=reference_number,
        posting_date=posting_date,
        journal_entry=journal_entry,
        posting_status='posted',
    )
    return journal_entry


@db_transaction.atomic
def post_intercompany_transaction(intercompany_transaction, acting_user=None):
    if intercompany_transaction.status in {'posted', 'eliminated'}:
        return intercompany_transaction

    source_entity = intercompany_transaction.source_entity
    destination_entity = intercompany_transaction.destination_entity
    amount = Decimal(str(intercompany_transaction.amount or 0)).quantize(Decimal('0.01'))
    posting_date = intercompany_transaction.transaction_date
    due_date = intercompany_transaction.due_date or posting_date
    description = intercompany_transaction.description or f'Intercompany {intercompany_transaction.get_transaction_type_display()}'

    ensure_period_is_open(source_entity, posting_date)
    ensure_period_is_open(destination_entity, posting_date)

    if intercompany_transaction.transaction_type in {'invoice', 'transfer_pricing', 'adjustment'}:
        source_customer = _ensure_internal_customer(source_entity, destination_entity)
        destination_vendor = _ensure_internal_vendor(destination_entity, source_entity)

        source_invoice = Invoice.objects.create(
            entity=source_entity,
            customer=source_customer,
            invoice_number=_make_reference('IC-INV', intercompany_transaction.reference_number),
            invoice_date=posting_date,
            due_date=due_date,
            subtotal=amount,
            tax_amount=DECIMAL_ZERO,
            total_amount=amount,
            paid_amount=DECIMAL_ZERO,
            outstanding_amount=amount,
            currency=intercompany_transaction.currency,
            status='posted',
            description=description,
            notes=intercompany_transaction.notes,
            created_by=acting_user or intercompany_transaction.created_by,
        )
        destination_bill = Bill.objects.create(
            entity=destination_entity,
            vendor=destination_vendor,
            bill_number=_make_reference('IC-BILL', intercompany_transaction.reference_number),
            bill_date=posting_date,
            due_date=due_date,
            subtotal=amount,
            tax_amount=DECIMAL_ZERO,
            total_amount=amount,
            paid_amount=DECIMAL_ZERO,
            outstanding_amount=amount,
            currency=intercompany_transaction.currency,
            status='posted',
            description=description,
            notes=intercompany_transaction.notes,
            created_by=acting_user or intercompany_transaction.created_by,
        )

        source_due_from = _find_or_create_account(
            source_entity,
            _account_code('13', destination_entity.id),
            f'Due from {destination_entity.name}',
            'asset',
        )
        source_revenue = _find_or_create_account(
            source_entity,
            _account_code('41', destination_entity.id),
            f'Intercompany revenue - {destination_entity.name}',
            'revenue',
        )
        destination_expense = _find_or_create_account(
            destination_entity,
            _account_code('51', source_entity.id),
            f'Intercompany expense - {source_entity.name}',
            'expense',
        )
        destination_due_to = _find_or_create_account(
            destination_entity,
            _account_code('23', source_entity.id),
            f'Due to {source_entity.name}',
            'liability',
        )

        source_journal = _create_journal_entry(
            source_entity,
            _make_reference('IC-JE-SRC', intercompany_transaction.reference_number),
            description,
            posting_date,
            acting_user or intercompany_transaction.created_by,
            source_due_from,
            source_revenue,
            amount,
        )
        destination_journal = _create_journal_entry(
            destination_entity,
            _make_reference('IC-JE-DST', intercompany_transaction.reference_number),
            description,
            posting_date,
            acting_user or intercompany_transaction.created_by,
            destination_expense,
            destination_due_to,
            amount,
        )

        intercompany_transaction.source_invoice = source_invoice
        intercompany_transaction.destination_bill = destination_bill
        intercompany_transaction.source_journal_entry = source_journal
        intercompany_transaction.destination_journal_entry = destination_journal

    elif intercompany_transaction.transaction_type == 'loan':
        destination_loan = Loan.objects.create(
            entity=destination_entity,
            organization=intercompany_transaction.organization,
            lender_name=f'{source_entity.name} (Intercompany)',
            loan_type='term_loan',
            loan_amount=amount,
            currency=intercompany_transaction.currency,
            interest_rate=intercompany_transaction.transfer_pricing_markup_percent,
            start_date=posting_date,
            maturity_date=due_date,
            status='active',
            principal_remaining=amount,
            monthly_payment=DECIMAL_ZERO,
        )

        source_loan_receivable = _find_or_create_account(
            source_entity,
            _account_code('14', destination_entity.id),
            f'Intercompany loan receivable - {destination_entity.name}',
            'asset',
        )
        source_settlement = _find_or_create_account(
            source_entity,
            _account_code('11', destination_entity.id),
            f'Intercompany settlement clearing - {destination_entity.name}',
            'asset',
        )
        destination_settlement = _find_or_create_account(
            destination_entity,
            _account_code('11', source_entity.id),
            f'Intercompany settlement clearing - {source_entity.name}',
            'asset',
        )
        destination_loan_payable = _find_or_create_account(
            destination_entity,
            _account_code('24', source_entity.id),
            f'Intercompany loan payable - {source_entity.name}',
            'liability',
        )

        source_journal = _create_journal_entry(
            source_entity,
            _make_reference('IC-LOAN-SRC', intercompany_transaction.reference_number),
            description,
            posting_date,
            acting_user or intercompany_transaction.created_by,
            source_loan_receivable,
            source_settlement,
            amount,
        )
        destination_journal = _create_journal_entry(
            destination_entity,
            _make_reference('IC-LOAN-DST', intercompany_transaction.reference_number),
            description,
            posting_date,
            acting_user or intercompany_transaction.created_by,
            destination_settlement,
            destination_loan_payable,
            amount,
        )

        intercompany_transaction.destination_loan = destination_loan
        intercompany_transaction.source_journal_entry = source_journal
        intercompany_transaction.destination_journal_entry = destination_journal
    else:
        raise ValueError('Unsupported intercompany transaction type.')

    intercompany_transaction.status = 'posted'
    intercompany_transaction.posted_at = timezone.now()
    intercompany_transaction.save()
    return intercompany_transaction


def _summarize_entity_financials(entity, as_of_date):
    ledgers = GeneralLedger.objects.filter(
        entity=entity,
        posting_status='posted',
        posting_date__lte=as_of_date,
    ).select_related('debit_account', 'credit_account')

    assets = Decimal('0.00')
    liabilities = Decimal('0.00')
    equity = Decimal('0.00')
    revenue = Decimal('0.00')
    expenses = Decimal('0.00')
    cash_movement = Decimal('0.00')

    for ledger_entry in ledgers:
        debit_delta = _signed_amount(ledger_entry.debit_account.account_type, ledger_entry.debit_amount, DECIMAL_ZERO)
        credit_delta = _signed_amount(ledger_entry.credit_account.account_type, DECIMAL_ZERO, ledger_entry.credit_amount)

        for account, delta in ((ledger_entry.debit_account, debit_delta), (ledger_entry.credit_account, credit_delta)):
            if account.account_type == 'asset':
                assets += delta
                if 'cash' in account.account_name.lower() or 'bank' in account.account_name.lower():
                    cash_movement += delta
            elif account.account_type == 'liability':
                liabilities += delta
            elif account.account_type == 'equity':
                equity += delta
            elif account.account_type == 'revenue':
                revenue += delta
            elif account.account_type == 'expense':
                expenses += delta

    pnl = {
        'revenue': float(revenue),
        'expenses': float(expenses),
        'net_income': float(revenue - expenses),
    }
    balance_sheet = {
        'assets': float(assets),
        'liabilities': float(liabilities),
        'equity': float(equity + (revenue - expenses)),
    }
    cashflow = {
        'operating_cashflow': float(cash_movement),
        'net_cashflow': float(cash_movement),
    }
    return pnl, balance_sheet, cashflow


@db_transaction.atomic
def run_consolidation_engine(consolidation):
    consolidation_entities = list(
        consolidation.entities.select_related('entity').all()
    )
    included_entity_ids = [item.entity_id for item in consolidation_entities]

    aggregated_revenue = Decimal('0.00')
    aggregated_expenses = Decimal('0.00')
    aggregated_assets = Decimal('0.00')
    aggregated_liabilities = Decimal('0.00')
    aggregated_equity = Decimal('0.00')
    aggregated_cashflow = Decimal('0.00')

    for consolidation_entity in consolidation_entities:
        pnl, balance_sheet, cashflow = _summarize_entity_financials(
            consolidation_entity.entity,
            consolidation.consolidation_date,
        )
        consolidation_entity.pnl_data = pnl
        consolidation_entity.balance_sheet_data = balance_sheet
        consolidation_entity.cashflow_data = cashflow
        consolidation_entity.save(update_fields=['pnl_data', 'balance_sheet_data', 'cashflow_data'])

        aggregated_revenue += Decimal(str(pnl['revenue']))
        aggregated_expenses += Decimal(str(pnl['expenses']))
        aggregated_assets += Decimal(str(balance_sheet['assets']))
        aggregated_liabilities += Decimal(str(balance_sheet['liabilities']))
        aggregated_equity += Decimal(str(balance_sheet['equity']))
        aggregated_cashflow += Decimal(str(cashflow['net_cashflow']))

    elimination_summary = {
        'revenue_expense': Decimal('0.00'),
        'receivable_payable': Decimal('0.00'),
        'loan_balance': Decimal('0.00'),
    }
    elimination_details = []
    IntercompanyEliminationEntry.objects.filter(consolidation=consolidation).delete()

    if consolidation.eliminate_intercompany and included_entity_ids:
        transactions = IntercompanyTransaction.objects.filter(
            organization=consolidation.organization,
            source_entity_id__in=included_entity_ids,
            destination_entity_id__in=included_entity_ids,
            status__in=['posted', 'eliminated'],
            transaction_date__lte=consolidation.consolidation_date,
        ).select_related('source_entity', 'destination_entity')

        for intercompany_transaction in transactions:
            amount = Decimal(str(intercompany_transaction.amount or 0)).quantize(Decimal('0.01'))
            if intercompany_transaction.transaction_type in {'invoice', 'transfer_pricing', 'adjustment'}:
                elimination_types = [
                    ('revenue_expense', {
                        'pnl': {
                            'revenue_reduction': float(amount),
                            'expense_reduction': float(amount),
                        }
                    }),
                    ('receivable_payable', {
                        'balance_sheet': {
                            'asset_reduction': float(amount),
                            'liability_reduction': float(amount),
                        }
                    }),
                ]
                elimination_summary['revenue_expense'] += amount
                elimination_summary['receivable_payable'] += amount
                aggregated_revenue -= amount
                aggregated_expenses -= amount
                aggregated_assets -= amount
                aggregated_liabilities -= amount
            elif intercompany_transaction.transaction_type == 'loan':
                elimination_types = [
                    ('loan_balance', {
                        'balance_sheet': {
                            'asset_reduction': float(amount),
                            'liability_reduction': float(amount),
                        }
                    }),
                ]
                elimination_summary['loan_balance'] += amount
                aggregated_assets -= amount
                aggregated_liabilities -= amount
            else:
                elimination_types = []

            for elimination_type, payload in elimination_types:
                elimination_entry = IntercompanyEliminationEntry.objects.create(
                    consolidation=consolidation,
                    transaction=intercompany_transaction,
                    elimination_type=elimination_type,
                    source_entity=intercompany_transaction.source_entity,
                    destination_entity=intercompany_transaction.destination_entity,
                    amount=amount,
                    currency=intercompany_transaction.currency,
                    adjustment_payload=payload,
                    notes=f'Automatically generated from {intercompany_transaction.reference_number}.',
                )
                elimination_details.append({
                    'id': elimination_entry.id,
                    'transaction_reference': intercompany_transaction.reference_number,
                    'elimination_type': elimination_type,
                    'amount': float(amount),
                    'currency': intercompany_transaction.currency,
                })
            intercompany_transaction.status = 'eliminated'
            intercompany_transaction.save(update_fields=['status', 'updated_at'])

    consolidated_pnl = {
        'revenue': float(aggregated_revenue),
        'expenses': float(aggregated_expenses),
        'net_income': float(aggregated_revenue - aggregated_expenses),
    }
    consolidated_balance_sheet = {
        'assets': float(aggregated_assets),
        'liabilities': float(aggregated_liabilities),
        'equity': float(aggregated_assets - aggregated_liabilities),
    }
    consolidated_cashflow = {
        'net_cashflow': float(aggregated_cashflow),
    }

    consolidation.consolidated_pnl = consolidated_pnl
    consolidation.consolidated_balance_sheet = consolidated_balance_sheet
    consolidation.consolidated_cashflow = consolidated_cashflow
    consolidation.adjustments = {
        'intercompany_eliminations': {
            'revenue_expense': float(elimination_summary['revenue_expense']),
            'receivable_payable': float(elimination_summary['receivable_payable']),
            'loan_balance': float(elimination_summary['loan_balance']),
            'details': elimination_details,
        }
    }
    consolidation.total_assets = aggregated_assets
    consolidation.total_liabilities = aggregated_liabilities
    consolidation.shareholders_equity = (aggregated_assets - aggregated_liabilities).quantize(Decimal('0.01'))
    consolidation.status = 'completed'
    consolidation.save(
        update_fields=[
            'consolidated_pnl', 'consolidated_balance_sheet', 'consolidated_cashflow', 'adjustments',
            'total_assets', 'total_liabilities', 'shareholders_equity', 'status', 'updated_at'
        ]
    )
    return consolidation
