apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ledgora-local

resources:
  - ../../base
  - namespace.yaml

patchesStrategicMerge:
  - patch-config.yaml
  - patch-ingress.yaml
  - patch-scale.yaml

images:
  - name: ledgora/backend
    newName: atonixdev/legdora-api
    newTag: latest
  - name: ledgora/banking-sync
    newName: atonixdev/legdora-banking-sync
    newTag: latest
  - name: ledgora/approval-digest
    newName: atonixdev/legdora-approval-digest
    newTag: latest
  - name: ledgora/app
    newName: atonixdev/legdora-app
    newTag: latest
