apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atonixcorp-local

resources:
  - ../../base
  - namespace.yaml

patchesStrategicMerge:
  - patch-config.yaml
  - patch-ingress.yaml
  - patch-scale.yaml

images:
  - name: atonixcorp/backend
    newName: atonixdev/legdora-api
    newTag: latest
  - name: atonixcorp/banking-sync
    newName: atonixdev/legdora-banking-sync
    newTag: latest
  - name: atonixcorp/approval-digest
    newName: atonixdev/legdora-approval-digest
    newTag: latest
  - name: atonixcorp/app
    newName: atonixdev/legdora-app
    newTag: latest
