apiVersion: v1
kind: ConfigMap
metadata:
  name: ledgora-config
data:
  DJANGO_DEBUG: "true"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,api.ledgora.local"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://app.ledgora.local"
  CSRF_TRUSTED_ORIGINS: "http://localhost:3000,http://app.ledgora.local"
  FRONTEND_BASE_URL: "http://app.ledgora.local"
  APPROVAL_NOTIFICATION_BASE_URL: "http://app.ledgora.local"
  DEPLOYMENT_ENVIRONMENT: local
  APP_VERSION: latest
