# Generated by Django 5.2.16 on 2026-07-22

from django.db import migrations, models
from django.utils import timezone


def backfill_workspace_codes(apps, schema_editor):
    Workspace = apps.get_model('workspaces', 'Workspace')
    IdentityCodeSequence = apps.get_model('finances', 'IdentityCodeSequence')
    year = timezone.now().year

    def next_code():
        sequence, _ = IdentityCodeSequence.objects.get_or_create(
            code_type='WSP',
            year=year,
            defaults={'last_value': 0},
        )
        sequence.last_value += 1
        sequence.save(update_fields=['last_value'])
        return f'AC-WSP-{year}-{sequence.last_value:04d}'

    for workspace in Workspace.objects.filter(workspace_code__isnull=True).order_by('pk'):
        workspace.workspace_code = next_code()
        workspace.save(update_fields=['workspace_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0052_public_identity_codes'),
        ('workspaces', '0006_workspacemember_member_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='workspace_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(backfill_workspace_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='workspace',
            name='workspace_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, unique=True),
        ),
    ]