import React, { createContext, useContext, useState, useMemo } from 'react';

const LanguageContext = createContext();

const MESSAGES = {
  en: {
    appName: 'AtonixCorp',
    languageName: 'English',
    nav: {
      home: 'Home',
      bookkeeping: 'Bookkeeping',
      myIncome: 'My Income',
      taxReturns: 'Tax & Returns',
      cashflowBudgets: 'Cashflow & Budgets',
      assetsLiabilities: 'Assets & Liabilities',
      insightsAlerts: 'Insights & Alerts',
      settings: 'Settings',
      orgOverview: 'Org Overview',
      entitiesCountries: 'Entities & Countries',
      cashflowTreasury: 'Cashflow & Treasury',
      taxCompliance: 'Tax & Compliance',
      riskExposure: 'Risk & Exposure',
      reportsExports: 'Reports & Exports',
      teamPermissions: 'Team & Permissions',
      enterpriseSettings: 'Settings & Integrations',
      logout: 'Logout',
    },
    auth: {
      login: 'Login',
      getStarted: 'Get Started',
    },
    dashboard: {
      title: 'Financial Dashboard',
      monthlyView: 'Monthly View',
      allTime: 'All-Time',
      noTransactions: 'No transactions found',
      loading: 'Loading...',
      budgetVsActual: 'Budget vs Actual Spending',
      noBudgetData: 'No budget data available',
      weeklyPattern: 'Weekly Spending Pattern',
      insights: 'Insights',
      highestSpending: 'Highest spending day was',
      with: 'with',
      noExpenseData: 'No expense data available',
      financialHealthScore: 'Financial Health Score',
      issues: 'Issues',
      warningTitle: 'Financial Issues Detected',
      resolved: 'Resolved',
      recentTransactions: 'Recent Transactions',
      category: 'Category',
      date: 'Date',
      amount: 'Amount',
      reference: 'Reference',
    },
    budget: {
      title: 'Budget Management',
      addBudget: '+ Add Budget',
      cancel: 'Cancel',
      createNew: 'Create New Budget',
      category: 'Category',
      categoryPlaceholder: 'e.g., Food, Transportation',
      limit: 'Budget Limit',
      limitPlaceholder: '$0.00',
      create: 'Create Budget',
      noBudgets: 'No budgets created yet. Start by adding a new budget!',
      spent: 'Spent',
      remaining: 'Remaining',
      percentUsed: 'Used',
    },
    labels: {
      totalIncome: 'Total Income',
      totalExpenses: 'Total Expenses',
      balance: 'Balance',
      tax: 'Tax',
      netIncome: 'Net Income',
      income: 'Income',
      expenses: 'Expenses',
      budget: 'Budget',
      spent: 'Spent',
      remaining: 'Remaining',
      assets: 'Assets',
      liabilities: 'Liabilities',
      overBudget: 'Over budget by',
      approachingLimit: 'Approaching budget limit',
    },
  },
  fr: {
    appName: 'AtonixCorp',
    languageName: 'Français',
    nav: {
      home: 'Accueil',
      bookkeeping: 'Comptabilité',
      myIncome: 'Mes revenus',
      taxReturns: 'Impôts & déclarations',
      cashflowBudgets: 'Trésorerie & budgets',
      assetsLiabilities: 'Actifs & passifs',
      insightsAlerts: 'Analyses & alertes',
      settings: 'Paramètres',
      orgOverview: "Vue d'ensemble",
      entitiesCountries: 'Entités & pays',
      cashflowTreasury: 'Trésorerie consolidée',
      taxCompliance: 'Fiscalité & conformité',
      riskExposure: 'Risques & expositions',
      reportsExports: 'Rapports & exports',
      teamPermissions: 'Équipe & droits',
      enterpriseSettings: 'Paramètres & intégrations',
      logout: 'Déconnexion',
    },
    auth: {
      login: 'Connexion',
      getStarted: 'Commencer',
    },
    dashboard: {
      title: 'Tableau de bord financier',
      monthlyView: 'Vue mensuelle',
      allTime: 'Tout le temps',
      noTransactions: 'Aucune transaction trouvée',
      loading: 'Chargement...',
      budgetVsActual: 'Budget vs Dépenses réelles',
      noBudgetData: 'Aucune donnée budgétaire disponible',
      weeklyPattern: 'Modèle de dépenses hebdomadaires',
      insights: 'Insights',
      highestSpending: 'Le jour le plus dépensier était',
      with: 'avec',
      noExpenseData: 'Aucune donnée de dépenses disponible',
      financialHealthScore: 'Score de santé financière',
      issues: 'Problèmes',
      warningTitle: 'Problèmes financiers détectés',
      resolved: 'Résolu',
      recentTransactions: 'Transactions récentes',
      category: 'Catégorie',
      date: 'Date',
      amount: 'Montant',
      reference: 'Référence',
    },
    budget: {
      title: 'Gestion du budget',
      addBudget: '+ Ajouter un budget',
      cancel: 'Annuler',
      createNew: 'Créer un nouveau budget',
      category: 'Catégorie',
      categoryPlaceholder: 'par exemple, Alimentation, Transport',
      limit: 'Limite budgétaire',
      limitPlaceholder: '$0,00',
      create: 'Créer un budget',
      noBudgets: 'Aucun budget créé. Commencez par ajouter un nouveau budget!',
      spent: 'Dépensé',
      remaining: 'Restant',
      percentUsed: 'Utilisé',
    },
    labels: {
      totalIncome: 'Revenu total',
      totalExpenses: 'Dépenses totales',
      balance: 'Solde',
      tax: 'Impôt',
      netIncome: 'Revenu net',
      income: 'Revenu',
      expenses: 'Dépenses',
      budget: 'Budget',
      spent: 'Dépensé',
      remaining: 'Restant',
      assets: 'Actifs',
      liabilities: 'Passifs',
      overBudget: 'Dépassement du budget de',
      approachingLimit: 'Approche de la limite budgétaire',
    },
  },
  es: {
    appName: 'AtonixCorp',
    languageName: 'Español',
    nav: {
      home: 'Inicio',
      bookkeeping: 'Contabilidad',
      myIncome: 'Mis Ingresos',
      taxReturns: 'Impuestos & Declaraciones',
      cashflowBudgets: 'Flujo de Caja & Presupuestos',
      assetsLiabilities: 'Activos & Pasivos',
      insightsAlerts: 'Análisis & Alertas',
      settings: 'Configuración',
      orgOverview: 'Descripción General',
      entitiesCountries: 'Entidades & Países',
      cashflowTreasury: 'Tesorería Consolidada',
      taxCompliance: 'Fiscalidad & Cumplimiento',
      riskExposure: 'Riesgos & Exposiciones',
      reportsExports: 'Reportes & Exportaciones',
      teamPermissions: 'Equipo & Permisos',
      enterpriseSettings: 'Configuración & Integraciones',
      logout: 'Cerrar Sesión',
    },
    auth: {
      login: 'Iniciar Sesión',
      getStarted: 'Comenzar',
    },
    dashboard: {
      title: 'Panel de Control Financiero',
      monthlyView: 'Vista Mensual',
      allTime: 'Todo el Tiempo',
      noTransactions: 'No se encontraron transacciones',
      loading: 'Cargando...',
      budgetVsActual: 'Presupuesto vs Gasto Real',
      noBudgetData: 'No hay datos de presupuesto disponibles',
      weeklyPattern: 'Patrón de Gasto Semanal',
      insights: 'Perspectivas',
      highestSpending: 'El día con mayor gasto fue',
      with: 'con',
      noExpenseData: 'No hay datos de gastos disponibles',
      financialHealthScore: 'Puntuación de Salud Financiera',
      issues: 'Problemas',
      warningTitle: 'Se detectaron problemas financieros',
      resolved: 'Resuelto',
      recentTransactions: 'Transacciones Recientes',
      category: 'Categoría',
      date: 'Fecha',
      amount: 'Cantidad',
      reference: 'Referencia',
    },
    budget: {
      title: 'Gestión de Presupuesto',
      addBudget: '+ Agregar Presupuesto',
      cancel: 'Cancelar',
      createNew: 'Crear Nuevo Presupuesto',
      category: 'Categoría',
      categoryPlaceholder: 'por ejemplo, Alimentos, Transporte',
      limit: 'Límite de Presupuesto',
      limitPlaceholder: '$0.00',
      create: 'Crear Presupuesto',
      noBudgets: '¡Aún no hay presupuestos creados. Comience agregando un nuevo presupuesto!',
      spent: 'Gastado',
      remaining: 'Restante',
      percentUsed: 'Usado',
    },
    labels: {
      totalIncome: 'Ingresos Totales',
      totalExpenses: 'Gastos Totales',
      balance: 'Saldo',
      tax: 'Impuesto',
      netIncome: 'Ingreso Neto',
      income: 'Ingreso',
      expenses: 'Gastos',
      budget: 'Presupuesto',
      spent: 'Gastado',
      remaining: 'Restante',
      assets: 'Activos',
      liabilities: 'Pasivos',
      overBudget: 'Exceso de presupuesto de',
      approachingLimit: 'Acercándose al límite de presupuesto',
    },
  },
  de: {
    appName: 'AtonixCorp',
    languageName: 'Deutsch',
    nav: {
      home: 'Startseite',
      bookkeeping: 'Buchhaltung',
      myIncome: 'Mein Einkommen',
      taxReturns: 'Steuern & Erklärungen',
      cashflowBudgets: 'Cashflow & Budgets',
      assetsLiabilities: 'Vermögenswerte & Verbindlichkeiten',
      insightsAlerts: 'Insights & Warnungen',
      settings: 'Einstellungen',
      orgOverview: 'Organisationsübersicht',
      entitiesCountries: 'Entitäten & Länder',
      cashflowTreasury: 'Konsolidierte Schatzkammer',
      taxCompliance: 'Steuereinhaltung',
      riskExposure: 'Risiko & Exposition',
      reportsExports: 'Berichte & Exporte',
      teamPermissions: 'Team & Berechtigungen',
      enterpriseSettings: 'Einstellungen & Integrationen',
      logout: 'Abmelden',
    },
    auth: {
      login: 'Anmelden',
      getStarted: 'Jetzt Beginnen',
    },
    dashboard: {
      title: 'Finanz-Dashboard',
      monthlyView: 'Monatsansicht',
      allTime: 'Gesamtzeit',
      noTransactions: 'Keine Transaktionen gefunden',
      loading: 'Lädt...',
      budgetVsActual: 'Budget vs. Tatsächliche Ausgaben',
      noBudgetData: 'Keine Budgetdaten verfügbar',
      weeklyPattern: 'Wöchentliches Ausgabenmuster',
      insights: 'Einblicke',
      highestSpending: 'Der Tag mit den höchsten Ausgaben war',
      with: 'mit',
      noExpenseData: 'Keine Ausgabendaten verfügbar',
      financialHealthScore: 'Finanzieller Gesundheitsscore',
      issues: 'Probleme',
      warningTitle: 'Finanzielle Probleme erkannt',
      resolved: 'Gelöst',
      recentTransactions: 'Letzte Transaktionen',
      category: 'Kategorie',
      date: 'Datum',
      amount: 'Betrag',
      reference: 'Referenz',
    },
    budget: {
      title: 'Budgetverwaltung',
      addBudget: '+ Budget hinzufügen',
      cancel: 'Abbrechen',
      createNew: 'Neues Budget erstellen',
      category: 'Kategorie',
      categoryPlaceholder: 'z.B. Lebensmittel, Verkehr',
      limit: 'Budgetlimit',
      limitPlaceholder: '$0.00',
      create: 'Budget erstellen',
      noBudgets: 'Noch keine Budgets erstellt. Fügen Sie ein neues Budget hinzu!',
      spent: 'Ausgegeben',
      remaining: 'Verbleibend',
      percentUsed: 'Verwendet',
    },
    labels: {
      totalIncome: 'Gesamteinkommen',
      totalExpenses: 'Gesamtausgaben',
      balance: 'Bilanz',
      tax: 'Steuern',
      netIncome: 'Nettoeinkommen',
      income: 'Einkommen',
      expenses: 'Ausgaben',
      budget: 'Budget',
      spent: 'Ausgegeben',
      remaining: 'Verbleibend',
      assets: 'Vermögenswerte',
      liabilities: 'Verbindlichkeiten',
      overBudget: 'Budget überschritten um',
      approachingLimit: 'Budgetlimit nähert sich',
    },
  },
  pt: {
    appName: 'AtonixCorp',
    languageName: 'Português',
    nav: {
      home: 'Início',
      bookkeeping: 'Contabilidade',
      myIncome: 'Minha Renda',
      taxReturns: 'Impostos & Declarações',
      cashflowBudgets: 'Fluxo de Caixa & Orçamentos',
      assetsLiabilities: 'Ativos & Passivos',
      insightsAlerts: 'Análises & Alertas',
      settings: 'Configurações',
      orgOverview: 'Visão Geral da Organização',
      entitiesCountries: 'Entidades & Países',
      cashflowTreasury: 'Tesouro Consolidado',
      taxCompliance: 'Conformidade Tributária',
      riskExposure: 'Riscos & Exposições',
      reportsExports: 'Relatórios & Exportações',
      teamPermissions: 'Equipe & Permissões',
      enterpriseSettings: 'Configurações & Integrações',
      logout: 'Sair',
    },
    auth: {
      login: 'Conectar',
      getStarted: 'Começar',
    },
    dashboard: {
      title: 'Painel Financeiro',
      monthlyView: 'Visualização Mensal',
      allTime: 'Desde o Início',
      noTransactions: 'Nenhuma transação encontrada',
      loading: 'Carregando...',
      budgetVsActual: 'Orçamento vs Gastos Reais',
      noBudgetData: 'Nenhum dado de orçamento disponível',
      weeklyPattern: 'Padrão de Gastos Semanais',
      insights: 'Insights',
      highestSpending: 'O dia com maior gasto foi',
      with: 'com',
      noExpenseData: 'Nenhum dado de despesas disponível',
      financialHealthScore: 'Pontuação de Saúde Financeira',
      issues: 'Problemas',
      warningTitle: 'Problemas financeiros detectados',
      resolved: 'Resolvido',
      recentTransactions: 'Transações Recentes',
      category: 'Categoria',
      date: 'Data',
      amount: 'Valor',
      reference: 'Referência',
    },
    budget: {
      title: 'Gerenciamento de Orçamento',
      addBudget: '+ Adicionar Orçamento',
      cancel: 'Cancelar',
      createNew: 'Criar Novo Orçamento',
      category: 'Categoria',
      categoryPlaceholder: 'por exemplo, Alimentos, Transporte',
      limit: 'Limite de Orçamento',
      limitPlaceholder: '$0.00',
      create: 'Criar Orçamento',
      noBudgets: 'Nenhum orçamento criado ainda. Comece adicionando um novo orçamento!',
      spent: 'Gasto',
      remaining: 'Restante',
      percentUsed: 'Usado',
    },
    labels: {
      totalIncome: 'Renda Total',
      totalExpenses: 'Despesas Totais',
      balance: 'Saldo',
      tax: 'Imposto',
      netIncome: 'Renda Líquida',
      income: 'Renda',
      expenses: 'Despesas',
      budget: 'Orçamento',
      spent: 'Gasto',
      remaining: 'Restante',
      assets: 'Ativos',
      liabilities: 'Passivos',
      overBudget: 'Excesso de orçamento de',
      approachingLimit: 'Aproximando-se do limite orçamentário',
    },
  },
  zh: {
    appName: 'AtonixCorp',
    languageName: '',
    nav: {
      home: '',
      bookkeeping: '',
      myIncome: '',
      taxReturns: '',
      cashflowBudgets: '',
      assetsLiabilities: '',
      insightsAlerts: '',
      settings: '',
      orgOverview: '',
      entitiesCountries: '',
      cashflowTreasury: '',
      taxCompliance: '',
      riskExposure: '',
      reportsExports: '',
      teamPermissions: '',
      enterpriseSettings: '',
      logout: '',
    },
    auth: {
      login: '',
      getStarted: '',
    },
    dashboard: {
      title: '',
      monthlyView: '',
      allTime: '',
      noTransactions: '',
      loading: '...',
      budgetVsActual: '',
      noBudgetData: '',
      weeklyPattern: '',
      insights: '',
      highestSpending: '',
      with: '',
      noExpenseData: '',
      financialHealthScore: '',
      issues: '',
      warningTitle: '',
      resolved: '',
      recentTransactions: '',
      category: '',
      date: '',
      amount: '',
      reference: '',
    },
    budget: {
      title: '',
      addBudget: '+ ',
      cancel: '',
      createNew: '',
      category: '',
      categoryPlaceholder: '',
      limit: '',
      limitPlaceholder: '$0.00',
      create: '',
      noBudgets: '!',
      spent: '',
      remaining: '',
      percentUsed: '',
    },
    labels: {
      totalIncome: '',
      totalExpenses: '',
      balance: '',
      tax: '',
      netIncome: '',
      income: '',
      expenses: '',
      budget: '',
      spent: '',
      remaining: '',
      assets: '',
      liabilities: '',
      overBudget: '',
      approachingLimit: '',
    },
  },
  ar: {
    appName: 'AtonixCorp',
    languageName: 'العربية',
    nav: {
      home: 'الرئيسية',
      bookkeeping: 'المحاسبة',
      myIncome: 'دخلي',
      taxReturns: 'الضرائب والإقرارات',
      cashflowBudgets: 'التدفق النقدي والميزانيات',
      assetsLiabilities: 'الأصول والالتزامات',
      insightsAlerts: 'الرؤى والتنبيهات',
      settings: 'الإعدادات',
      orgOverview: 'نظرة عامة على المنظمة',
      entitiesCountries: 'الكيانات والدول',
      cashflowTreasury: 'الخزانة الموحدة',
      taxCompliance: 'الامتثال الضريبي',
      riskExposure: 'المخاطر والتعرض',
      reportsExports: 'التقارير والتصديرات',
      teamPermissions: 'الفريق والأذونات',
      enterpriseSettings: 'الإعدادات والتكاملات',
      logout: 'تسجيل الخروج',
    },
    auth: {
      login: 'تسجيل الدخول',
      getStarted: 'ابدأ',
    },
    dashboard: {
      title: 'لوحة التحكم المالية',
      monthlyView: ' العرض الشهري',
      allTime: ' طوال الوقت',
      noTransactions: 'لم يتم العثور على معاملات',
      loading: 'جاري التحميل...',
      budgetVsActual: 'الميزانية مقابل النفقات الفعلية',
      noBudgetData: 'لا توجد بيانات ميزانية متاحة',
      weeklyPattern: 'نمط الإنفاق الأسبوعي',
      insights: 'الرؤى',
      highestSpending: 'كان يوم الإنفاق الأعلى',
      with: 'مع',
      noExpenseData: 'لا توجد بيانات نفقات متاحة',
      financialHealthScore: 'درجة الصحة المالية',
      issues: 'مشاكل',
      warningTitle: 'تم اكتشاف مشاكل مالية',
      resolved: 'تم الحل',
      recentTransactions: 'المعاملات الأخيرة',
      category: 'فئة',
      date: 'التاريخ',
      amount: 'المبلغ',
      reference: 'المرجع',
    },
    budget: {
      title: 'إدارة الميزانية',
      addBudget: '+ إضافة ميزانية',
      cancel: 'إلغاء',
      createNew: 'إنشاء ميزانية جديدة',
      category: 'فئة',
      categoryPlaceholder: 'على سبيل المثال، الغذاء والنقل',
      limit: 'حد الميزانية',
      limitPlaceholder: '$0.00',
      create: 'إنشاء ميزانية',
      noBudgets: 'لم يتم إنشاء أي ميزانيات حتى الآن. ابدأ بإضافة ميزانية جديدة!',
      spent: 'تم الإنفاق',
      remaining: 'المتبقي',
      percentUsed: 'مستخدمة',
    },
    labels: {
      totalIncome: 'إجمالي الدخل',
      totalExpenses: 'إجمالي النفقات',
      balance: 'الرصيد',
      tax: 'الضريبة',
      netIncome: 'صافي الدخل',
      income: 'الدخل',
      expenses: 'النفقات',
      budget: 'الميزانية',
      spent: 'تم الإنفاق',
      remaining: 'المتبقي',
      assets: 'الأصول',
      liabilities: 'الالتزامات',
      overBudget: 'تجاوز الميزانية بمقدار',
      approachingLimit: 'الاقتراب من حد الميزانية',
    },
  },
};

export const LANGUAGE_LIST = [
  { code: 'en', label: 'English' },
  { code: 'fr', label: 'Français' },
  { code: 'es', label: 'Español' },
  { code: 'de', label: 'Deutsch' },
  { code: 'pt', label: 'Português' },
  { code: 'zh', label: '' },
  { code: 'ar', label: 'العربية' },
];

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Initialize language from localStorage if available, otherwise default to 'en'
    const savedLanguage = localStorage.getItem('selectedLanguage');
    return savedLanguage || 'en';
  });

  const handleSetLanguage = (newLanguage) => {
    setLanguage(newLanguage);
    localStorage.setItem('selectedLanguage', newLanguage);
  };

  const value = useMemo(() => {
    const messages = MESSAGES[language] || MESSAGES.en;

    const t = (path) => {
      const segments = path.split('.');
      let current = messages;
      for (const segment of segments) {
        if (!current || typeof current !== 'object') return path;
        current = current[segment];
      }
      return current || path;
    };

    return {
      language,
      setLanguage: handleSetLanguage,
      t,
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
