import React, { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';

import { useEnterprise } from '../../context/EnterpriseContext';
import './EnterpriseActionPages.css';
import './EnterpriseTaxCompliance.css';

const EnterpriseTaxCompliance = () => {
  const [searchParams, setSearchParams] = useSearchParams();
  const activeSection = searchParams.get('section') || 'overview';

  const {
    entities,
    fetchEntityTaxProfiles,
    createTaxProfile,
    fetchEntityComplianceDocuments,
    fetchEntityComplianceDeadlines,
    fetchEntityTaxCalculations,
    createComplianceDeadline,
    createComplianceDocument,
  } = useEnterprise();

  const [selectedEntityId, setSelectedEntityId] = useState('');
  const selectedEntity = useMemo(() => {
    if (!selectedEntityId) return null;
    return entities.find((e) =>String(e.id) === String(selectedEntityId)) || null;
  }, [entities, selectedEntityId]);

  const [taxProfiles, setTaxProfiles] = useState([]);
  const [documents, setDocuments] = useState([]);
  const [complianceDeadlines, setComplianceDeadlines] = useState([]);
  const [taxCalculations, setTaxCalculations] = useState([]);
  const [dataError, setDataError] = useState(null);

  const [showCountrySelector, setShowCountrySelector] = useState(false);

  // Calculator state
  const [calcForm, setCalcForm] = useState({
    calcType: 'corporate',
    jurisdiction: '',
    taxYear: new Date().getFullYear(),
    income: '',
    rate: '',
    deductions: '',
    credits: '',
  });
  const [calcResult, setCalcResult] = useState(null);

  // Filing / deadline creation state
  const [showDeadlineForm, setShowDeadlineForm] = useState(false);
  const [deadlineForm, setDeadlineForm] = useState({ title: '', deadline_type: 'tax_return', deadline_date: '' });
  const [deadlineSubmitting, setDeadlineSubmitting] = useState(false);

  // Document upload state
  const [showDocForm, setShowDocForm] = useState(false);
  const [docForm, setDocForm] = useState({ title: '', document_type: 'tax_certificate', notes: '' });
  const [docSubmitting, setDocSubmitting] = useState(false);

  useEffect(() => {
    if (selectedEntityId) return;
    if (!entities || entities.length === 0) return;
    setSelectedEntityId(String(entities[0].id));
  }, [entities, selectedEntityId]);

  useEffect(() => {
    const load = async () => {
      if (!selectedEntityId) return;
      setDataError(null);
      try {
        const [profiles, docs, deadlines, calcs] = await Promise.all([
          fetchEntityTaxProfiles(selectedEntityId),
          fetchEntityComplianceDocuments(selectedEntityId),
          fetchEntityComplianceDeadlines(selectedEntityId),
          fetchEntityTaxCalculations(selectedEntityId),
        ]);

        const uiProfiles = (profiles || []).map((p) => ({
          id: p.id,
          country: p.country,
          status: p.status,
          lastUpdated: p.updated_at || p.created_at,
          entities: 1,
          taxRules: {
            ...(p.tax_rules || {}),
            lastRuleUpdate: p.last_rule_update || null,
            autoUpdate: p.auto_update !== false,
          },
          residencyStatus: p.residency_status || 'detected',
          complianceScore: Number.isFinite(p.compliance_score) ? p.compliance_score : 0,
        }));

        const uiDocuments = (docs || []).map((d) => {
          const typeMap = {
            license: 'form',
            registration: 'form',
            tax_certificate: 'form',
            insurance: 'report',
            permit: 'form',
            contract: 'audit',
            certificate: 'form',
            other: 'report',
          };
          const statusMap = {
            active: 'ready',
            renewed: 'ready',
            expiring_soon: 'ready',
            expired: 'failed',
          };

          return {
            id: d.id,
            name: d.title,
            type: typeMap[d.document_type] || 'report',
            status: statusMap[d.status] || 'ready',
            size: d.file_path ? '—' : '-',
            date: d.created_at || d.issue_date,
            autoGenerated: false,
            raw: d,
          };
        });

        setTaxProfiles(uiProfiles);
        setDocuments(uiDocuments);
        setComplianceDeadlines(deadlines || []);
        setTaxCalculations(calcs || []);
      } catch (err) {
        console.error(err);
        setDataError(err?.message || 'Failed to load Tax & Compliance data');
        setTaxProfiles([]);
        setDocuments([]);
        setComplianceDeadlines([]);
        setTaxCalculations([]);
      }
    };

    load();
  }, [
    selectedEntityId,
    fetchEntityTaxProfiles,
    fetchEntityComplianceDocuments,
    fetchEntityComplianceDeadlines,
    fetchEntityTaxCalculations,
  ]);

  const complianceAlerts = useMemo(() => {
    const now = new Date();
    return (complianceDeadlines || []).map((d) => {
      const deadlineDate = d.deadline_date ? new Date(d.deadline_date) : null;
      const daysLeft = deadlineDate ? Math.ceil((deadlineDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24)) : null;

      let severity = 'low';
      if (d.status === 'overdue') severity = 'high';
      else if (daysLeft !== null && daysLeft <= 7) severity = 'high';
      else if (daysLeft !== null && daysLeft <= 30) severity = 'medium';

      return {
        id: d.id,
        type: 'deadline',
        message: d.title,
        severity,
        date: d.deadline_date,
        autoGenerated: false,
        actions: ['view', 'set-reminder'],
        raw: d,
      };
    });
  }, [complianceDeadlines]);

  const calculations = useMemo(() => {
    const empty = {
      incomeTax: { amount: 0, breakdown: { salary: 0, business: 0 }, lastCalculated: null },
      capitalGains: { amount: 0, breakdown: { stocks: 0, crypto: 0 }, lastCalculated: null },
      dividends: { amount: 0, breakdown: { qualified: 0, ordinary: 0 }, lastCalculated: null },
      withholding: { amount: 0, breakdown: { federal: 0, state: 0 }, lastCalculated: null },
      vat: { amount: 0, breakdown: { sales: 0, imports: 0 }, lastCalculated: null },
      quarterlyProjection: { amount: 0, confidence: 0, lastProjected: null },
    };

    if (!Array.isArray(taxCalculations) || taxCalculations.length === 0) return empty;

    const sorted = [...taxCalculations].sort((a, b) => {
      const ad = new Date(a.created_at || 0).getTime();
      const bd = new Date(b.created_at || 0).getTime();
      return bd - ad;
    });

    const latestCorporate = sorted.find((c) => c.calculation_type === 'corporate') || null;
    const latestVat = sorted.find((c) => c.calculation_type === 'vat') || null;

    return {
      ...empty,
      incomeTax: latestCorporate
        ? {
            amount: Number(latestCorporate.calculated_tax || 0),
            breakdown: { salary: 0, business: Number(latestCorporate.taxable_income || 0) },
            lastCalculated: latestCorporate.created_at || null,
          }
        : empty.incomeTax,
      vat: latestVat
        ? {
            amount: Number(latestVat.calculated_tax || 0),
            breakdown: { sales: Number(latestVat.taxable_income || 0), imports: 0 },
            lastCalculated: latestVat.created_at || null,
          }
        : empty.vat,
    };
  }, [taxCalculations]);

  const overallComplianceScore = useMemo(() => {
    if (!Array.isArray(taxProfiles) || taxProfiles.length === 0) return 0;
    const avg = taxProfiles.reduce((sum, p) => sum + (Number.isFinite(p.complianceScore) ? p.complianceScore : 0), 0) / taxProfiles.length;
    return Math.max(0, Math.min(100, Math.round(avg)));
  }, [taxProfiles]);

  const overallComplianceLabel = useMemo(() => {
    if (overallComplianceScore >= 90) return { label: 'Excellent', className: 'excellent' };
    if (overallComplianceScore >= 75) return { label: 'Good', className: 'good' };
    if (overallComplianceScore >= 50) return { label: 'Fair', className: 'fair' };
    return { label: 'Needs Attention', className: 'warning' };
  }, [overallComplianceScore]);

  const recentActivityItems = useMemo(() => {
    const items = [];
    const latestProfile = Array.isArray(taxProfiles) && taxProfiles.length
      ? [...taxProfiles].sort((a, b) => new Date(b.lastUpdated || 0) - new Date(a.lastUpdated || 0))[0]
      : null;
    if (latestProfile?.lastUpdated) {
      items.push({
        key: `profile-${latestProfile.id}`,
        kind: 'info',
        message: `Tax profile updated for ${latestProfile.country}`,
        when: latestProfile.lastUpdated,
        action: 'View',
      });
    }

    const latestCalc = Array.isArray(taxCalculations) && taxCalculations.length
      ? [...taxCalculations].sort((a, b) => new Date(b.created_at || 0) - new Date(a.created_at || 0))[0]
      : null;
    if (latestCalc?.created_at) {
      items.push({
        key: `calc-${latestCalc.id}`,
        kind: 'success',
        message: `Tax calculation saved (${latestCalc.calculation_type} - ${latestCalc.jurisdiction})`,
        when: latestCalc.created_at,
        action: 'View',
      });
    }

    const latestDoc = Array.isArray(documents) && documents.length
      ? [...documents].sort((a, b) => new Date(b.date || 0) - new Date(a.date || 0))[0]
      : null;
    if (latestDoc?.date) {
      items.push({
        key: `doc-${latestDoc.id}`,
        kind: 'success',
        message: `Compliance document updated (${latestDoc.name})`,
        when: latestDoc.date,
        action: 'View',
      });
    }

    return items.slice(0, 4);
  }, [taxProfiles, taxCalculations, documents]);

  const upcomingDeadlines = useMemo(() => {
    const list = Array.isArray(complianceDeadlines) ? [...complianceDeadlines] : [];
    list.sort((a, b) => new Date(a.deadline_date || 0) - new Date(b.deadline_date || 0));
    return list.slice(0, 5);
  }, [complianceDeadlines]);

  // Available countries for tax profiles
  const availableCountries = [
    { code: 'US', name: 'United States', flag: '', taxTypes: ['federal', 'state'], autoDetectable: true },
    { code: 'UK', name: 'United Kingdom', flag: '', taxTypes: ['corporation'], autoDetectable: true },
    { code: 'CA', name: 'Canada', flag: '', taxTypes: ['federal', 'provincial'], autoDetectable: true },
    { code: 'DE', name: 'Germany', flag: '', taxTypes: ['corporate'], autoDetectable: false },
    { code: 'FR', name: 'France', flag: '', taxTypes: ['corporate'], autoDetectable: false },
    { code: 'AU', name: 'Australia', flag: '', taxTypes: ['corporate'], autoDetectable: true },
    { code: 'ZA', name: 'South Africa', flag: '', taxTypes: ['corporate'], autoDetectable: false },
    { code: 'SG', name: 'Singapore', flag: '', taxTypes: ['corporate'], autoDetectable: false },
  ];

  const handleCountrySelect = async (countryCode) => {
    setShowCountrySelector(false);

    if (!selectedEntityId) return;

    const selected = availableCountries.find((c) => c.code === countryCode);
    const countryName = selected?.name || countryCode;

    try {
      await createTaxProfile({
        entity: selectedEntityId,
        country: countryName,
        status: 'active',
        tax_rules: {},
        auto_update: true,
        residency_status: 'detected',
      });
      const refreshed = await fetchEntityTaxProfiles(selectedEntityId);
      const uiProfiles = (refreshed || []).map((p) => ({
        id: p.id,
        country: p.country,
        status: p.status,
        lastUpdated: p.updated_at || p.created_at,
        entities: 1,
        taxRules: {
          ...(p.tax_rules || {}),
          lastRuleUpdate: p.last_rule_update || null,
          autoUpdate: p.auto_update !== false,
        },
        residencyStatus: p.residency_status || 'detected',
        complianceScore: Number.isFinite(p.compliance_score) ? p.compliance_score : 0,
      }));
      setTaxProfiles(uiProfiles);
    } catch (err) {
      console.error(err);
      setDataError(err?.message || 'Failed to add tax profile');
    }
  };

  const handleCalculate = (e) => {
    e.preventDefault();
    const income = parseFloat(calcForm.income) || 0;
    const rate = parseFloat(calcForm.rate) || 0;
    const deductions = parseFloat(calcForm.deductions) || 0;
    const credits = parseFloat(calcForm.credits) || 0;

    const taxableIncome = Math.max(0, income - deductions);
    const calculatedTax = (taxableIncome * rate) / 100 - credits;

    setCalcResult({
      taxableIncome,
      rate,
      calculatedTax: Math.max(0, calculatedTax),
      deductions,
      credits,
      effectiveRate: income > 0 ? (Math.max(0, calculatedTax) / income) * 100 : 0,
      calcType: calcForm.calcType,
      jurisdiction: calcForm.jurisdiction || 'Global',
      taxYear: calcForm.taxYear,
    });
  };

  const handleAddDeadline = async (e) => {
    e.preventDefault();
    if (!deadlineForm.title.trim() || !deadlineForm.deadline_date || !selectedEntityId) {
      alert('Please fill in all required fields');
      return;
    }

    setDeadlineSubmitting(true);
    try {
      await createComplianceDeadline({
        entity: selectedEntityId,
        title: deadlineForm.title,
        deadline_type: deadlineForm.deadline_type,
        deadline_date: deadlineForm.deadline_date,
      });
      const refreshed = await fetchEntityComplianceDeadlines(selectedEntityId);
      setComplianceDeadlines(refreshed || []);
      setShowDeadlineForm(false);
      setDeadlineForm({ title: '', deadline_type: 'tax_return', deadline_date: '' });
    } catch (err) {
      console.error(err);
      alert(err?.message || 'Failed to add deadline');
    } finally {
      setDeadlineSubmitting(false);
    }
  };

  const renderOverview = () => (
    <div className="compliance-overview">
      {/* Quick Stats */}
      <div className="overview-stats">
        <div className="stat-card stat-card-blue">
          <div className="stat-icon stat-icon-globe"></div>
          <div className="stat-content">
            <h3>{taxProfiles.filter(p => p.status === 'active').length}</h3>
            <p>Active Countries</p>
            <span className="stat-trend neutral">Based on entity profiles</span>
          </div>
        </div>
        <div className="stat-card stat-card-green">
          <div className="stat-icon stat-icon-calc">$</div>
          <div className="stat-content">
            <h3>${calculations.quarterlyProjection.amount.toLocaleString()}</h3>
            <p>Quarterly Projection</p>
            <span className="stat-trend neutral">No projection model yet</span>
          </div>
        </div>
        <div className="stat-card stat-card-red">
          <div className="stat-icon stat-icon-alert">!</div>
          <div className="stat-content">
            <h3>{complianceAlerts.filter(a => a.severity === 'high').length}</h3>
            <p>Critical Alerts</p>
            <span className="stat-trend neutral">Derived from deadlines</span>
          </div>
        </div>
        <div className="stat-card stat-card-purple">
          <div className="stat-icon stat-icon-docs">&#9679;</div>
          <div className="stat-content">
            <h3>{documents.filter(d => d.status === 'ready').length}</h3>
            <p>Ready Documents</p>
            <span className="stat-trend neutral">From compliance vault</span>
          </div>
        </div>
      </div>

      {/* Quick Actions Bar */}
      <div className="quick-actions">
        <button className="quick-action-btn" onClick={() => setSearchParams({ section: 'calculator' })}>
          Run Tax Calculation
        </button>
        <button className="quick-action-btn secondary" onClick={() => setSearchParams({ section: 'monitoring' })}>
          Check Compliance
        </button>
        <button className="quick-action-btn secondary" onClick={() => setSearchParams({ section: 'filing' })}>
          Filing Assistant
        </button>
        <button className="quick-action-btn secondary" onClick={() => setSearchParams({ section: 'documents' })}>
          View Documents
        </button>
      </div>

      {/* Compliance Health Dashboard */}
      <div className="compliance-health">
        <div className="health-header">
          <h3>Compliance Health Score</h3>
          <div className="health-score">
            <div className="score-circle">
              <span className="score-number">{overallComplianceScore}</span>
              <span className="score-label">/100</span>
            </div>
            <div className="score-details">
              <span className={`score-status ${overallComplianceLabel.className}`}>{overallComplianceLabel.label}</span>
              <span className="score-change">Calculated from profiles</span>
            </div>
          </div>
        </div>

        <div className="health-metrics">
          <div className="metric-item">
            <div className="metric-label">Tax Profiles</div>
            <div className="metric-bar">
              <div className="metric-fill" style={{width: `${taxProfiles.length ? Math.min(100, overallComplianceScore) : 0}%`}}></div>
            </div>
            <span className="metric-value">{overallComplianceScore}%</span>
          </div>
          <div className="metric-item">
            <div className="metric-label">Documents</div>
            <div className="metric-bar">
              <div className="metric-fill" style={{width: `${documents.length ? 100 : 0}%`}}></div>
            </div>
            <span className="metric-value">{documents.length}</span>
          </div>
          <div className="metric-item">
            <div className="metric-label">Upcoming Deadlines</div>
            <div className="metric-bar">
              <div className="metric-fill" style={{width: `${upcomingDeadlines.length ? 100 : 0}%`}}></div>
            </div>
            <span className="metric-value">{upcomingDeadlines.length}</span>
          </div>
        </div>
      </div>

      {/* Recent Activity */}
      <div className="recent-activity">
        <h3>Recent Activity</h3>
        <div className="activity-list">
          {recentActivityItems.length === 0 ? (
            <div className="activity-item">
              <div className="activity-icon info"></div>
              <div className="activity-content">
                <p>No activity yet for this entity</p>
                <span>Create a tax profile, upload a document, or run a calculation</span>
              </div>
            </div>
          ) : (
            recentActivityItems.map((item) => (
              <div key={item.key} className="activity-item">
                <div className={`activity-icon ${item.kind}`}> </div>
                <div className="activity-content">
                  <p>{item.message}</p>
                  <span>{item.when ? new Date(item.when).toLocaleString() : ''}</span>
                </div>
                <button className="btn-link">{item.action}</button>
              </div>
            ))
          )}
        </div>
      </div>

      {/* Upcoming Deadlines */}
      <div className="upcoming-deadlines">
        <h3>Upcoming Deadlines</h3>
        <div className="deadlines-list">
          {upcomingDeadlines.length === 0 ? (
            <div className="deadline-item normal">
              <div className="deadline-info">
                <h4>No deadlines yet</h4>
                <p>Create compliance deadlines for the selected entity</p>
              </div>
              <div className="deadline-status">
                <span className="status-badge normal">Empty</span>
              </div>
            </div>
          ) : (
            upcomingDeadlines.map((d) => (
              <div key={d.id} className={`deadline-item ${d.status === 'overdue' || d.status === 'due_soon' ? 'urgent' : 'normal'}`}>
                <div className="deadline-info">
                  <h4>{d.title}</h4>
                  <p>{d.deadline_type}</p>
                  <span className="deadline-date">Due: {d.deadline_date ? new Date(d.deadline_date).toLocaleDateString() : '—'}</span>
                </div>
                <div className="deadline-status">
                  <span className={`status-badge ${d.status === 'overdue' || d.status === 'due_soon' ? 'urgent' : 'normal'}`}>{d.status}</span>
                </div>
                <div className="deadline-actions">
                  <button className="btn-secondary">View</button>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );

  const renderTaxProfiles = () => (
    <div className="tax-profiles-section">
      <div className="section-header">
        <h2>Multi-Country Tax Profiles</h2>
        <p>Auto-configured tax rules for global operations</p>
        <div className="header-actions">
          <button
            className="btn-secondary"
            onClick={() => setShowCountrySelector(true)}
          >
            Add Country
          </button>
          <button className="btn-link">
            Update All Rules
          </button>
        </div>
      </div>

      {/* Country Selector Modal */}
      {showCountrySelector && (
        <div className="modal-overlay" onClick={() => setShowCountrySelector(false)}>
          <div className="modal-content country-selector" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3>Select Country for Tax Profile</h3>
              <button className="close-btn" onClick={() => setShowCountrySelector(false)}>

              </button>
            </div>
            <div className="country-grid">
              {availableCountries.map(country => (
                <div
                  key={country.code}
                  className="country-option"
                  onClick={() => handleCountrySelect(country.code)}
                >
                  <div className="country-flag">{country.flag}</div>
                  <div className="country-info">
                    <h4>{country.name}</h4>
                    <div className="country-details">
                      <span className="tax-types">
                        {country.taxTypes.join(', ')}
                      </span>
                      {country.autoDetectable && (
                        <span className="auto-detect-badge">Auto-detectable</span>
                      )}
                    </div>
                  </div>

                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      <div className="profiles-grid">
        {taxProfiles.map(profile => (
          <div key={profile.id} className="profile-card">
            <div className="profile-header">
              <div className="country-flag country-code-badge">
                {availableCountries.find(c => c.name === profile.country || c.code === profile.country)?.code || profile.country.slice(0, 2).toUpperCase()}
              </div>
              <div className={`status-badge ${profile.status}`}>
                {profile.status}
              </div>
              <div className="compliance-score">

                <span>{profile.complianceScore}%</span>
              </div>
            </div>
            <div className="profile-content">
              <h3>{availableCountries.find(c => c.code === profile.country)?.name || profile.country} Tax Profile</h3>

              <div className="profile-stats">
                <div className="stat">
                  <span className="label">Entities:</span>
                  <span className="value">{profile.entities}</span>
                </div>
                <div className="stat">
                  <span className="label">Last Updated:</span>
                  <span className="value">{new Date(profile.lastUpdated).toLocaleDateString()}</span>
                </div>
                <div className="stat">
                  <span className="label">Residency:</span>
                  <span className={`value ${profile.residencyStatus}`}>
                    {profile.residencyStatus}
                  </span>
                </div>
              </div>

              {/* Tax Rules Preview */}
              <div className="tax-rules-preview">
                <h4>Current Tax Rules</h4>
                <div className="rules-list">
                  {profile.taxRules?.federalRate != null && (
                    <div className="rule-item">
                      <span>Federal Rate:</span>
                      <span>{profile.taxRules.federalRate}%</span>
                    </div>
                  )}
                  {profile.taxRules?.corporationTax != null && (
                    <div className="rule-item">
                      <span>Corporation Tax:</span>
                      <span>{profile.taxRules.corporationTax}%</span>
                    </div>
                  )}
                  {profile.taxRules?.vatRate != null && (
                    <div className="rule-item">
                      <span>VAT Rate:</span>
                      <span>{profile.taxRules.vatRate}%</span>
                    </div>
                  )}
                  {profile.taxRules?.stateRates?.CA != null && (
                    <div className="rule-item">
                      <span>State (CA):</span>
                      <span>{profile.taxRules.stateRates.CA}%</span>
                    </div>
                  )}
                  {profile.taxRules?.provincialRates?.ON != null && (
                    <div className="rule-item">
                      <span>Provincial (ON):</span>
                      <span>{profile.taxRules.provincialRates.ON}%</span>
                    </div>
                  )}
                  {!profile.taxRules?.federalRate && !profile.taxRules?.corporationTax && !profile.taxRules?.vatRate && (
                    <div className="rule-item">
                      <span>No tax rules configured yet</span>
                    </div>
                  )}
                </div>
                <div className="rule-update-info">
                  {profile.taxRules?.lastRuleUpdate && (
                    <span>Last rule update: {new Date(profile.taxRules.lastRuleUpdate).toLocaleDateString()}</span>
                  )}
                  {profile.taxRules?.autoUpdate && (
                    <span className="auto-update-badge">Auto-updating</span>
                  )}
                </div>
              </div>
            </div>
            <div className="profile-actions">
              <button className="btn-secondary">Configure</button>
              <button className="btn-link">View Rules</button>
              <button className="btn-link">Edit Profile</button>
            </div>
          </div>
        ))}
      </div>

      <div className="auto-update-notice">

        <div className="notice-content">
          <h4>Automatic Updates Active</h4>
          <p>Tax rules are automatically updated when changes are detected in supported jurisdictions. Last global update: January 10, 2025</p>
          <div className="update-stats">
            <span>247 jurisdictions monitored</span>
            <span>12 rule changes this month</span>
            <span>99.9% uptime</span>
          </div>
        </div>
      </div>

      {/* Residency Detection Section */}
      <div className="residency-detection">
        <h3>Residency Status Detection</h3>
        <p>Automatically detect and confirm tax residency status across jurisdictions</p>
        <div className="detection-controls">
          <button className="btn-primary">
            Run Detection Scan
          </button>
          <button className="btn-secondary">
            Review Detected Status
          </button>
        </div>
        <div className="detection-results">
          <div className="result-item">

            <span>US Residency: Confirmed (based on entity registrations)</span>
          </div>
          <div className="result-item">

            <span>UK Residency: Confirmed (based on permanent establishment)</span>
          </div>
          <div className="result-item">

            <span>CA Residency: Pending verification (awaiting additional documentation)</span>
          </div>
        </div>
      </div>
    </div>
  );

  const renderCalculator = () => (
    <div className="tax-calculator-section">
      <div className="section-header">
        <h2>Tax Calculator</h2>
        <p>Quick tax calculations for corporate, VAT, and personal income</p>
      </div>

      <div className="calculator-grid">
        {/* Calculation Input Form */}
        <form className="tax-calc-form" onSubmit={handleCalculate}>
          <div className="tax-calc-field">
            <label>Calculation Type</label>
            <select value={calcForm.calcType} onChange={(e) => setCalcForm({ ...calcForm, calcType: e.target.value })}>
              <option value="corporate">Corporate Tax</option>
              <option value="vat">VAT/GST</option>
              <option value="personal">Personal Income</option>
            </select>
          </div>
          <div className="tax-calc-field">
            <label>Jurisdiction</label>
            <input type="text" placeholder="E.g., US/CA, UK, Germany" value={calcForm.jurisdiction} onChange={(e) => setCalcForm({ ...calcForm, jurisdiction: e.target.value })} />
          </div>
          <div className="tax-calc-field">
            <label>Tax Year</label>
            <input type="number" value={calcForm.taxYear} onChange={(e) => setCalcForm({ ...calcForm, taxYear: parseInt(e.target.value) })} />
          </div>
          <div className="tax-calc-field">
            <label>Gross Income / Revenue ($)</label>
            <input type="number" placeholder="0.00" value={calcForm.income} onChange={(e) => setCalcForm({ ...calcForm, income: e.target.value })} />
          </div>
          <div className="tax-calc-field">
            <label>Tax Rate (%)</label>
            <input type="number" step="0.01" placeholder="0.00" value={calcForm.rate} onChange={(e) => setCalcForm({ ...calcForm, rate: e.target.value })} />
          </div>
          <div className="tax-calc-field">
            <label>Deductions / Expenses ($)</label>
            <input type="number" placeholder="0.00" value={calcForm.deductions} onChange={(e) => setCalcForm({ ...calcForm, deductions: e.target.value })} />
          </div>
          <div className="tax-calc-field">
            <label>Credits / Offsets ($)</label>
            <input type="number" placeholder="0.00" value={calcForm.credits} onChange={(e) => setCalcForm({ ...calcForm, credits: e.target.value })} />
          </div>
          <button type="submit" className="btn-primary" style={{ gridColumn: '1 / -1' }}>Calculate Tax</button>
        </form>

        {/* Calculation Result */}
        {calcResult ? (
          <div className="calculation-result">
            <div className="result-header">
              <h3>Calculation Result</h3>
              <span className="calc-type-badge">{calcResult.calcType}</span>
            </div>
            <div className="result-summary">
              <div className="result-stat">
                <span className="label">Gross Income</span>
                <span className="amount">${calcResult.taxableIncome ? (parseFloat(calcResult.rate) * parseFloat(calcResult.taxableIncome) / 100 + parseFloat(calcResult.credits)).toLocaleString('en-US', { maximumFractionDigits: 2 }) : (parseFloat(calcForm.income) || 0).toLocaleString('en-US', { maximumFractionDigits: 2 })}</span>
              </div>
              <div className="result-stat">
                <span className="label">Taxable Income</span>
                <span className="amount">${calcResult.taxableIncome.toLocaleString('en-US', { maximumFractionDigits: 2 })}</span>
              </div>
              <div className="result-stat">
                <span className="label">Tax Rate</span>
                <span className="amount">{calcResult.rate}%</span>
              </div>
              <div className="result-stat">
                <span className="label">Tax Due</span>
                <span className="amount" style={{ fontSize: '1.4rem', fontWeight: 800, color: '#1f5f9b' }}>${calcResult.calculatedTax.toLocaleString('en-US', { maximumFractionDigits: 2 })}</span>
              </div>
            </div>
            <div className="calc-breakdown">
              <h4>Breakdown</h4>
              <div className="breakdown-rows">
                <div className="breakdown-row">
                  <span>Gross Income:</span>
                  <span>${(calcResult.taxableIncome + calcResult.deductions).toLocaleString('en-US', { maximumFractionDigits: 2 })}</span>
                </div>
                <div className="breakdown-row">
                  <span>Deductions:</span>
                  <span>-${calcResult.deductions.toLocaleString('en-US', { maximumFractionDigits: 2 })}</span>
                </div>
                <div className="breakdown-row">
                  <span>Taxable Base:</span>
                  <span>${calcResult.taxableIncome.toLocaleString('en-US', { maximumFractionDigits: 2 })}</span>
                </div>
                <div className="breakdown-row">
                  <span>Tax ({calcResult.rate}%):</span>
                  <span>${(calcResult.taxableIncome * calcResult.rate / 100).toLocaleString('en-US', { maximumFractionDigits: 2 })}</span>
                </div>
                <div className="breakdown-row">
                  <span>Credits:</span>
                  <span>-${calcResult.credits.toLocaleString('en-US', { maximumFractionDigits: 2 })}</span>
                </div>
                <div className="breakdown-row final">
                  <span>Total Tax Due:</span>
                  <span>${calcResult.calculatedTax.toLocaleString('en-US', { maximumFractionDigits: 2 })}</span>
                </div>
              </div>
              <div className="effective-rate">
                <span>Effective Tax Rate: {calcResult.effectiveRate.toFixed(2)}%</span>
              </div>
            </div>
          </div>
        ) : null}
      </div>

      {/* Previous Calculations History */}
      <div className="calculation-history">
        <h3>Saved Calculations</h3>
        <div className="history-list">
          {taxCalculations && taxCalculations.length > 0 ? (
            taxCalculations.slice(0, 5).map((calc) => (
              <div key={calc.id} className="history-item">
                <div className="item-icon"></div>
                <div className="item-content">
                  <h4>{calc.calculation_type} — {calc.jurisdiction || 'Global'}</h4>
                  <p>Tax Year: {calc.tax_year || 'Not specified'}</p>
                  <span className="item-date">{new Date(calc.created_at).toLocaleDateString()}</span>
                </div>
                <div className="item-amount">
                  <span className="amount">${(calc.calculated_tax || 0).toLocaleString('en-US', { maximumFractionDigits: 2 })}</span>
                </div>
              </div>
            ))
          ) : (
            <div className="no-history">
              <p>No saved calculations yet</p>
              <span>Run a calculation above to create a record</span>
            </div>
          )}
        </div>
      </div>
    </div>
  );

  const renderDocuments = () => (
    <div className="documents-section">
      <div className="section-header">
        <h2>Compliance Documents</h2>
        <p>Tax, regulatory, and compliance artifacts</p>
        <div className="header-actions">
          <button className="btn-secondary" onClick={() => setShowDocForm(true)}>
            Upload Document
          </button>
        </div>
      </div>

      {showDocForm && (
        <div className="modal-overlay" onClick={() => setShowDocForm(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h3>Upload Compliance Document</h3>
              <button className="close-btn" onClick={() => setShowDocForm(false)}>×</button>
            </div>
            <form onSubmit={async (e) => {
              e.preventDefault();
              setDocSubmitting(true);
              try {
                await createComplianceDocument({
                  entity: selectedEntityId,
                  title: docForm.title,
                  document_type: docForm.document_type,
                  notes: docForm.notes,
                });
                const refreshed = await fetchEntityComplianceDocuments(selectedEntityId);
                setDocuments((refreshed || []).map(d => ({
                  id: d.id,
                  name: d.title,
                  type: d.document_type === 'license' ? 'form' : d.document_type === 'tax_certificate' ? 'form' : 'report',
                  status: 'ready',
                  date: d.created_at,
                  raw: d,
                })));
                setShowDocForm(false);
                setDocForm({ title: '', document_type: 'tax_certificate', notes: '' });
              } catch (err) {
                alert(err?.message || 'Failed to upload document');
              } finally {
                setDocSubmitting(false);
              }
            }}>
              <div className="form-grid">
                <div className="form-field">
                  <label>Document Title</label>
                  <input type="text" required value={docForm.title} onChange={(e) => setDocForm({ ...docForm, title: e.target.value })} />
                </div>
                <div className="form-field">
                  <label>Document Type</label>
                  <select value={docForm.document_type} onChange={(e) => setDocForm({ ...docForm, document_type: e.target.value })}>
                    <option value="tax_certificate">Tax Certificate</option>
                    <option value="registration">Registration</option>
                    <option value="license">License</option>
                    <option value="permit">Permit</option>
                    <option value="contract">Contract</option>
                    <option value="insurance">Insurance</option>
                    <option value="other">Other</option>
                  </select>
                </div>
                <div className="form-field" style={{ gridColumn: '1 / -1' }}>
                  <label>Notes</label>
                  <textarea value={docForm.notes} onChange={(e) => setDocForm({ ...docForm, notes: e.target.value })} placeholder="Optional notes about this document" />
                </div>
              </div>
              <button type="submit" className="btn-primary" disabled={docSubmitting}>{docSubmitting ? 'Uploading...' : 'Upload Document'}</button>
            </form>
          </div>
        </div>
      )}

      <div className="documents-list">
        {documents && documents.length > 0 ? (
          documents.map((doc) => (
            <div key={doc.id} className="document-card">
              <div className="doc-icon"></div>
              <div className="doc-content">
                <h4>{doc.name}</h4>
                <p>{doc.type} — {new Date(doc.date).toLocaleDateString()}</p>
                <span className={`status-badge ${doc.status}`}>{doc.status}</span>
              </div>
              <div className="doc-actions">
                <button className="btn-secondary">Download</button>
              </div>
            </div>
          ))
        ) : (
          <div className="no-documents">
            <p>No documents uploaded yet</p>
            <span>Upload your first compliance document to get started</span>
            <button className="btn-primary" onClick={() => setShowDocForm(true)}>Upload Now</button>
          </div>
        )}
      </div>
    </div>
  );

  const renderMonitoring = () => (
    <div className="monitoring-section">
      <div className="section-header">
        <h2>Compliance Monitoring</h2>
        <p>Real-time alerts and deadline tracking</p>
      </div>

      <div className="monitoring-stats">
        <div className="stat-card stat-card-blue">
          <span className="stat-icon">&#9673;</span>
          <div className="stat-content">
            <h3>{taxProfiles.length}</h3>
            <p>Active Profiles</p>
            <span className="stat-trend neutral">Watched jurisdictions</span>
          </div>
        </div>
        <div className="stat-card stat-card-red">
          <span className="stat-icon">!</span>
          <div className="stat-content">
            <h3>{complianceAlerts.filter(a => a.severity === 'high').length}</h3>
            <p>Critical Alerts</p>
            <span className="stat-trend neutral">High-severity items</span>
          </div>
        </div>
        <div className="stat-card stat-card-orange">
          <span className="stat-icon">&#9650;</span>
          <div className="stat-content">
            <h3>{complianceAlerts.filter(a => {
              const d = new Date(a.date);
              const now = new Date();
              return d < now;
            }).length}</h3>
            <p>Overdue Items</p>
            <span className="stat-trend neutral">Past deadline</span>
          </div>
        </div>
        <div className="stat-card stat-card-amber">
          <span className="stat-icon">&#9201;</span>
          <div className="stat-content">
            <h3>{complianceAlerts.filter(a => {
              const d = new Date(a.date);
              const now = new Date();
              const daysUntil = Math.ceil((d.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
              return daysUntil > 0 && daysUntil <= 30;
            }).length}</h3>
            <p>In Next 30 Days</p>
            <span className="stat-trend neutral">Coming due soon</span>
          </div>
        </div>
      </div>

      <div className="alerts-panel">
        <h3>Active Compliance Alerts</h3>
        <div className="alerts-list">
          {complianceAlerts && complianceAlerts.length > 0 ? (
            complianceAlerts.map((alert) => {
              const d = new Date(alert.date);
              const now = new Date();
              const daysLeft = Math.ceil((d.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
              return (
                <div key={alert.id} className={`alert-item severity-${alert.severity}`}>
                  <div className="alert-icon"></div>
                  <div className="alert-content">
                    <h4>{alert.message}</h4>
                    <p>{alert.raw?.deadline_type || 'Compliance deadline'}</p>
                    <span className="alert-date">
                      {daysLeft < 0 ? `Overdue by ${Math.abs(daysLeft)} days` : `Due in ${daysLeft} days`}
                    </span>
                  </div>
                  <div className="alert-status">
                    <span className={`status-badge ${alert.severity}`}>{alert.severity} Priority</span>
                  </div>
                </div>
              );
            })
          ) : (
            <div className="no-alerts">
              <p>No active alerts</p>
              <span>All compliance obligations are current</span>
            </div>
          )}
        </div>
      </div>
    </div>
  );

  const renderVault = () => (
    <div className="vault-section">
      <div className="section-header">
        <h2>Compliance Vault</h2>
        <p>Secure storage for sensitive compliance documents</p>
      </div>
      <div className="vault-content">
        <div className="vault-stats">
          <div className="stat-card stat-card-blue">
            <span className="stat-icon">&#128193;</span>
            <div className="stat-content">
              <h3>{documents.length}</h3>
              <p>Stored Documents</p>
              <span className="stat-trend neutral">In compliance vault</span>
            </div>
          </div>
          <div className="stat-card stat-card-green">
            <span className="stat-icon">&#128274;</span>
            <div className="stat-content">
              <h3>AES-256</h3>
              <p>Encryption Standard</p>
              <span className="stat-trend neutral">Military grade</span>
            </div>
          </div>
          <div className="stat-card stat-card-purple">
            <span className="stat-icon">&#128065;</span>
            <div className="stat-content">
              <h3>24/7</h3>
              <p>Access Monitoring</p>
              <span className="stat-trend neutral">Continuous audit</span>
            </div>
          </div>
          <div className="stat-card stat-card-amber">
            <span className="stat-icon">&#10003;</span>
            <div className="stat-content">
              <h3>100%</h3>
              <p>Availability</p>
              <span className="stat-trend neutral">SLA guaranteed</span>
            </div>
          </div>
        </div>

        <div className="vault-organization">
          <h3>Organized Documents</h3>
          <div className="documents-list">
            {documents && documents.length > 0 ? (
              documents.map((doc) => (
                <div key={doc.id} className="document-card">
                  <div className="doc-icon"></div>
                  <div className="doc-content">
                    <h4>{doc.name}</h4>
                    <p>{doc.type}</p>
                  </div>
                  <div className="doc-security">
                    <span className="security-badge">Encrypted</span>
                  </div>
                </div>
              ))
            ) : (
              <p>No documents in vault</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );

  const renderFiling = () => {
    const now = new Date();
    const overdueCount = upcomingDeadlines.filter((deadline) => new Date(deadline.deadline_date) < now).length;
    const dueSoonCount = upcomingDeadlines.filter((deadline) => {
      const daysLeft = Math.ceil((new Date(deadline.deadline_date).getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
      return daysLeft >= 0 && daysLeft <= 30;
    }).length;

    return (
    <div className="filing-section">
      <div className="filing-hero-card">
        <div className="filing-hero-copy">
          <span className="filing-kicker">Dashboard Compliance — Filing</span>
          <h2>Filing &amp; Submission Assistance</h2>
          <p>Guided tax filing and form preparation across all jurisdictions.</p>
          <div className="header-actions">
            <button className="btn-primary" onClick={() => setShowDeadlineForm(true)}>
              Add Deadline
            </button>
            <button className="btn-secondary" onClick={() => setSearchParams({ section: 'documents' })}>
              Open Document Vault
            </button>
          </div>
        </div>
        <div className="filing-hero-aside">
          <div className="filing-status-badge">Submission Control Center</div>
          <div className="filing-hero-note">
            <strong>{upcomingDeadlines.length}</strong>
            <span>tracked filing obligations for the selected entity</span>
          </div>
        </div>
      </div>

      <div className="filing-summary-grid">
        <div className="filing-summary-card">
          <span className="filing-summary-label">Open Calendar</span>
          <strong className="filing-summary-value">{upcomingDeadlines.length}</strong>
          <span className="filing-summary-caption">Scheduled filings and submissions</span>
        </div>
        <div className="filing-summary-card warning">
          <span className="filing-summary-label">Overdue</span>
          <strong className="filing-summary-value">{overdueCount}</strong>
          <span className="filing-summary-caption">Deadlines that need immediate action</span>
        </div>
        <div className="filing-summary-card accent">
          <span className="filing-summary-label">Due In 30 Days</span>
          <strong className="filing-summary-value">{dueSoonCount}</strong>
          <span className="filing-summary-caption">Returns entering the submission window</span>
        </div>
        <div className="filing-summary-card muted">
          <span className="filing-summary-label">Supporting Docs</span>
          <strong className="filing-summary-value">{documents.length}</strong>
          <span className="filing-summary-caption">Artifacts ready for filing packages</span>
        </div>
      </div>

      {showDeadlineForm && (
        <div className="modal-overlay" onClick={() => setShowDeadlineForm(false)}>
          <div className="modal-content deadline-modal" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <div className="deadline-modal-heading">
                <span className="deadline-modal-kicker">Filing Calendar</span>
                <h3>Add Compliance Deadline</h3>
              </div>
              <button className="close-btn" onClick={() => setShowDeadlineForm(false)}>×</button>
            </div>
            <p className="deadline-modal-copy">Create a filing task with a title, due date, and type so the compliance queue can surface it by urgency.</p>
            <form onSubmit={handleAddDeadline}>
              <div className="form-grid">
                <div className="form-field" style={{ gridColumn: '1 / -1' }}>
                  <label>Deadline Title</label>
                  <input type="text" required placeholder="E.g., Q4 Tax Return Filing" value={deadlineForm.title} onChange={(e) => setDeadlineForm({ ...deadlineForm, title: e.target.value })} />
                </div>
                <div className="form-field">
                  <label>Deadline Type</label>
                  <select value={deadlineForm.deadline_type} onChange={(e) => setDeadlineForm({ ...deadlineForm, deadline_type: e.target.value })}>
                    <option value="tax_return">Tax Return</option>
                    <option value="payment">Tax Payment</option>
                    <option value="filing">Regulatory Filing</option>
                    <option value="renewal">Renewal</option>
                    <option value="audit">Audit Response</option>
                  </select>
                </div>
                <div className="form-field">
                  <label>Due Date</label>
                  <input type="date" required value={deadlineForm.deadline_date} onChange={(e) => setDeadlineForm({ ...deadlineForm, deadline_date: e.target.value })} />
                </div>
              </div>
              <div className="deadline-modal-footer">
                <div className="deadline-modal-note">This deadline will appear in the filing queue immediately after creation.</div>
                <button type="submit" className="btn-primary" disabled={deadlineSubmitting}>{deadlineSubmitting ? 'Adding...' : 'Add Deadline'}</button>
              </div>
            </form>
          </div>
        </div>
      )}

      <div className="filing-board">
        <section className="upcoming-filings filing-column">
          <div className="filing-column-header">
            <div>
              <h3>Upcoming Filings &amp; Deadlines</h3>
              <p>Submission queue ordered by urgency and due date.</p>
            </div>
            <span className="filing-column-pill">Live Queue</span>
          </div>
          <div className="filings-list filing-timeline">
            {upcomingDeadlines && upcomingDeadlines.length > 0 ? (
              upcomingDeadlines.map((deadline) => {
                const d = new Date(deadline.deadline_date);
                const daysLeft = Math.ceil((d.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
                const filingState = daysLeft < 0 ? 'urgent' : daysLeft <= 7 ? 'warning' : 'normal';
                return (
                  <div key={deadline.id} className={`filing-item ${filingState}`}>
                    <div className="filing-icon"></div>
                    <div className="filing-content">
                      <div className="filing-item-top">
                        <h4>{deadline.title}</h4>
                        <span className={`filing-chip ${filingState}`}>{deadline.deadline_type.replace('_', ' ')}</span>
                      </div>
                      <p>Submission package aligned to the selected entity and jurisdiction.</p>
                      <span className="filing-days">
                        {daysLeft < 0 ? `Overdue by ${Math.abs(daysLeft)} days` : `Due in ${daysLeft} days`}
                      </span>
                    </div>
                    <div className="filing-date">
                      <span>{new Date(deadline.deadline_date).toLocaleDateString()}</span>
                    </div>
                  </div>
                );
              })
            ) : (
              <div className="no-filings">
                <p>No upcoming filings scheduled</p>
                <span>Start by creating the first deadline for this entity.</span>
                <button className="btn-primary" onClick={() => setShowDeadlineForm(true)}>Create Deadline</button>
              </div>
            )}
          </div>
        </section>

        <aside className="filing-playbook filing-column">
          <div className="filing-column-header">
            <div>
              <h3>Submission Playbook</h3>
              <p>Operational steps for accurate preparation and on-time submission.</p>
            </div>
            <span className="filing-column-pill neutral">Guided Flow</span>
          </div>
          <div className="filing-step-list">
            <div className="filing-step-card active">
              <span className="filing-step-index">01</span>
              <div>
                <h4>Assemble return inputs</h4>
                <p>Pull entity tax calculations, residency rules, and jurisdiction-specific support documents.</p>
              </div>
            </div>
            <div className="filing-step-card">
              <span className="filing-step-index">02</span>
              <div>
                <h4>Validate package completeness</h4>
                <p>Check filing templates, attachments, and payment references before submission.</p>
              </div>
            </div>
            <div className="filing-step-card">
              <span className="filing-step-index">03</span>
              <div>
                <h4>Submit and track response</h4>
                <p>Record acknowledgment numbers, filing statuses, and any regulator follow-up items.</p>
              </div>
            </div>
          </div>
        </aside>
      </div>

      <div className="filing-assistance">
        <div className="filing-column-header">
          <div>
            <h3>Filing Support Modules</h3>
            <p>Reusable assets for submission, review, and regulator response handling.</p>
          </div>
          <span className="filing-column-pill accent">Toolkit</span>
        </div>
        <div className="assistance-grid">
          <div className="assistance-card">
            <div className="card-icon"></div>
            <h4>Tax Return Templates</h4>
            <p>Pre-filled forms and schedules for recurring filing scenarios.</p>
            <button className="btn-secondary">View Templates</button>
          </div>
          <div className="assistance-card">
            <div className="card-icon"></div>
            <h4>Filing Checklists</h4>
            <p>Step-by-step controls to review forms, payments, and evidence.</p>
            <button className="btn-secondary">View Checklists</button>
          </div>
          <div className="assistance-card">
            <div className="card-icon"></div>
            <h4>Extension Requests</h4>
            <p>Escalation guidance for deadline extensions and exception handling.</p>
            <button className="btn-secondary">Learn More</button>
          </div>
          <div className="assistance-card">
            <div className="card-icon"></div>
            <h4>Filing Status</h4>
            <p>Track submissions, regulator acknowledgments, and response cycles.</p>
            <button className="btn-secondary">View Status</button>
          </div>
        </div>
      </div>
    </div>
    );
  };

  const renderContent = () => {
    switch (activeSection) {
      case 'overview': return renderOverview();
      case 'profiles': return renderTaxProfiles();
      case 'calculator': return renderCalculator();
      case 'documents': return renderDocuments();
      case 'monitoring': return renderMonitoring();
      case 'vault': return renderVault();
      case 'filing': return renderFiling();
      default: return renderOverview();
    }
  };

  return (
    <div className="enterprise-tax-compliance enterprise-action-page">
      <section className="action-page-hero">
        <div className="action-page-copy">
          <span className="action-page-kicker">Workspace — Tax & Compliance</span>
          <h1 className="action-page-title">Tax & Compliance</h1>
          <p className="action-page-subtitle">Monitor deadlines, filings, tax calculations, and jurisdiction risk from one operational control surface.</p>
          <div className="action-page-actions">
            <select
              className="entity-selector"
              value={selectedEntityId}
              onChange={(e) => setSelectedEntityId(e.target.value)}
              disabled={!entities || entities.length === 0}
            >
              {(!entities || entities.length === 0) ? (
                <option value="">No entities</option>
              ) : (
                entities.map((ent) => (
                  <option key={ent.id} value={String(ent.id)}>
                    {ent.name} ({ent.country})
                  </option>
                ))
              )}
            </select>
            {dataError ? <span className="status-badge warning">{dataError}</span> : null}
          </div>
        </div>
        <div className="action-page-badge">{selectedEntity?.country || 'Global'}</div>
      </section>

      <section className="action-page-stats">
        <div className="action-page-stat">
          <span className="action-page-stat-label">Compliance Score</span>
          <span className="action-page-stat-value">{overallComplianceScore}%</span>
          <span className="action-page-stat-caption">Current organization-wide compliance posture</span>
        </div>
        <div className="action-page-stat">
          <span className="action-page-stat-label">Active Alerts</span>
          <span className="action-page-stat-value">{complianceAlerts.length}</span>
          <span className="action-page-stat-caption">Critical and upcoming obligations requiring attention</span>
        </div>
        <div className="action-page-stat">
          <span className="action-page-stat-label">Documents</span>
          <span className="action-page-stat-value">{documents.length}</span>
          <span className="action-page-stat-caption">Compliance artifacts currently attached to the selected entity</span>
        </div>
      </section>

      {/* Section Navigation Header */}
      <div className="section-navigation">
        <button
          className={`nav-btn ${activeSection === 'overview' ? 'active' : ''}`}
          onClick={() => setSearchParams({ section: 'overview' })}
        >
          Overview
        </button>
        <button
          className={`nav-btn ${activeSection === 'profiles' ? 'active' : ''}`}
          onClick={() => setSearchParams({ section: 'profiles' })}
        >
          Tax Profiles
        </button>
        <button
          className={`nav-btn ${activeSection === 'calculator' ? 'active' : ''}`}
          onClick={() => setSearchParams({ section: 'calculator' })}
        >
          Tax Calculator
        </button>
        <button
          className={`nav-btn ${activeSection === 'documents' ? 'active' : ''}`}
          onClick={() => setSearchParams({ section: 'documents' })}
        >
          Documents
        </button>
        <button
          className={`nav-btn ${activeSection === 'monitoring' ? 'active' : ''}`}
          onClick={() => setSearchParams({ section: 'monitoring' })}
        >
          Monitoring
        </button>
        <button
          className={`nav-btn ${activeSection === 'vault' ? 'active' : ''}`}
          onClick={() => setSearchParams({ section: 'vault' })}
        >
          Vault
        </button>
        <button
          className={`nav-btn ${activeSection === 'filing' ? 'active' : ''}`}
          onClick={() => setSearchParams({ section: 'filing' })}
        >
          Filing
        </button>
      </div>

      {/* Main Content */}
      <div className="compliance-main">
        {/* Content Area */}
        <div className="compliance-content">
          {renderContent()}
        </div>
      </div>
    </div>
  );
};

export default EnterpriseTaxCompliance;
