---
# roles/lgx-common/defaults/main.yml
# Baseline defaults for all Ledgora hosts.

atc_timezone: UTC
atc_ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org

atc_log_dir: /var/log/ledgora
ledgora_app_user: ledgora
ledgora_app_group: ledgora

atc_security_packages:
  - unattended-upgrades
  - aide
  - auditd
  - fail2ban

atc_required_packages:
  - curl
  - wget
  - jq
  - ca-certificates
  - gnupg
  - lsb-release
  - python3-pip
  - docker.io
  - docker-compose-plugin
