# Generated by Django 4.2.7 on 2026-03-15 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_developer_portal_content(apps, schema_editor):
    DeveloperAPICategory = apps.get_model('finances', 'DeveloperAPICategory')
    DeveloperAPITag = apps.get_model('finances', 'DeveloperAPITag')
    DeveloperAPI = apps.get_model('finances', 'DeveloperAPI')
    DeveloperAPIVersion = apps.get_model('finances', 'DeveloperAPIVersion')
    DeveloperAPIEndpoint = apps.get_model('finances', 'DeveloperAPIEndpoint')

    category_map = {}
    for index, category in enumerate([
        ('Markets', 'markets', 'Real-time and historical market data.'),
        ('Accounts', 'accounts', 'Accounts, balances, and portfolio state.'),
        ('Transactions', 'transactions', 'Transaction and activity history.'),
        ('Risk', 'risk', 'Risk, exposure, and operating limits.'),
        ('Reporting', 'reporting', 'Operational and regulatory reporting data.'),
        ('Reference Data', 'reference-data', 'Symbols, instruments, and metadata.'),
    ]):
        obj, _ = DeveloperAPICategory.objects.get_or_create(
            slug=category[1],
            defaults={'name': category[0], 'description': category[2], 'display_order': index},
        )
        category_map[obj.slug] = obj

    tag_map = {}
    for tag in [
        ('real-time', 'real-time'),
        ('historical', 'historical'),
        ('balances', 'balances'),
        ('positions', 'positions'),
        ('trades', 'trades'),
        ('limits', 'limits'),
        ('compliance', 'compliance'),
        ('metadata', 'metadata'),
    ]:
        obj, _ = DeveloperAPITag.objects.get_or_create(slug=tag[1], defaults={'name': tag[0]})
        tag_map[obj.slug] = obj

    api_specs = [
        {
            'slug': 'market-data-api',
            'name': 'Market Data API',
            'description': 'Secure access to real-time and end-of-day price, quote, and reference data.',
            'overview': 'Use this API to retrieve institutional-grade market data for valuation, execution support, and downstream reporting workflows.',
            'use_cases': [
                'Retrieve live FX and equity quotes for portfolio valuation.',
                'Pull end-of-day market closes for NAV and reporting jobs.',
            ],
            'data_domains': ['instruments', 'quotes', 'prices'],
            'data_types': ['real-time', 'end-of-day', 'historical'],
            'status': 'stable',
            'access_level': 'public',
            'auth_type': 'api_key',
            'compliance_notes': 'Redistribution and extended caching are subject to AtonixCorp data licensing and confidentiality controls.',
            'rate_limits': {'per_minute': 120, 'per_hour': 5000, 'burst': 'higher limits may apply for approved market-data clients'},
            'keywords': ['quotes', 'prices', 'market data', 'fx', 'equities'],
            'is_featured': True,
            'featured_rank': 1,
            'categories': ['markets', 'reference-data'],
            'tags': ['real-time', 'historical', 'metadata'],
            'version': {
                'version': 'v1',
                'base_path': '/v1/market',
                'summary': 'First stable release of the market data domain.',
                'status': 'stable',
                'is_default': True,
            },
            'endpoints': [
                {
                    'name': 'Get latest quotes',
                    'method': 'GET',
                    'path': '/v1/market/quotes',
                    'summary': 'Retrieve latest quotes for one or more instruments.',
                    'description': 'Returns the latest bid, ask, mid, and timestamp for supported symbols.',
                    'query_params': [
                        {'name': 'symbols', 'type': 'string', 'required': True, 'description': 'Comma-separated instrument symbols.'},
                        {'name': 'venue', 'type': 'string', 'required': False, 'description': 'Optional venue or market center filter.'},
                    ],
                    'headers': [
                        {'name': 'Authorization', 'required': True, 'description': 'Bearer or API key-derived access token.'},
                        {'name': 'X-Organization-Id', 'required': True, 'description': 'Tenant routing header.'},
                    ],
                    'scopes': ['market.read'],
                    'request_example': 'curl -X GET "https://api.atonixcorp.com/v1/market/quotes?symbols=EURUSD,AAPL" -H "Authorization: Bearer <token>" -H "X-Organization-Id: org_123"',
                    'response_example': '{"data":[{"symbol":"EURUSD","bid":1.0841,"ask":1.0843,"mid":1.0842,"timestamp":"2026-03-15T12:00:00Z"}]}',
                    'error_responses': [
                        {'status': 400, 'code': 'INVALID_REQUEST', 'message': 'symbols is required.'},
                        {'status': 401, 'code': 'UNAUTHORIZED', 'message': 'Missing or invalid credentials.'},
                        {'status': 429, 'code': 'RATE_LIMITED', 'message': 'Too many market data requests.'},
                    ],
                    'keywords': ['quotes', 'latest prices', 'fx', 'equity'],
                    'display_order': 1,
                },
            ],
        },
        {
            'slug': 'accounts-balances-api',
            'name': 'Accounts & Balances API',
            'description': 'Read account, balance, and position state across supported AtonixCorp organizations.',
            'overview': 'Use this API to retrieve current balances, cash positions, and account metadata used by treasury and operations teams.',
            'use_cases': [
                'Display current available balances in a treasury dashboard.',
                'Reconcile external systems against AtonixCorp account snapshots.',
            ],
            'data_domains': ['accounts', 'balances', 'positions'],
            'data_types': ['real-time', 'metadata'],
            'status': 'stable',
            'access_level': 'partner',
            'auth_type': 'oauth2',
            'compliance_notes': 'Access is limited to authorized account-owning or delegated organizations. All account reads are audited.',
            'rate_limits': {'per_minute': 60, 'per_hour': 2000},
            'keywords': ['accounts', 'balances', 'positions'],
            'is_featured': True,
            'featured_rank': 2,
            'categories': ['accounts'],
            'tags': ['balances', 'positions'],
            'version': {
                'version': 'v1',
                'base_path': '/v1/accounts',
                'summary': 'Stable read-side account and balance services.',
                'status': 'stable',
                'is_default': True,
            },
            'endpoints': [
                {
                    'name': 'List accounts',
                    'method': 'GET',
                    'path': '/v1/accounts',
                    'summary': 'List ledger and operational accounts.',
                    'description': 'Returns organization-scoped account records with current balance snapshots.',
                    'headers': [
                        {'name': 'Authorization', 'required': True, 'description': 'Bearer token.'},
                        {'name': 'X-Organization-Id', 'required': True, 'description': 'Tenant routing header.'},
                    ],
                    'scopes': ['accounts.read'],
                    'request_example': 'curl -X GET "https://api.atonixcorp.com/v1/accounts" -H "Authorization: Bearer <token>" -H "X-Organization-Id: org_123"',
                    'response_example': '[{"id":"acc_1","code":"1000","name":"Cash","type":"asset","current_balance":100000.0}]',
                    'error_responses': [
                        {'status': 403, 'code': 'INSUFFICIENT_SCOPE', 'message': 'Missing required API scope(s): accounts.read'},
                    ],
                    'keywords': ['accounts', 'balances'],
                    'display_order': 1,
                },
            ],
        },
        {
            'slug': 'transactions-api',
            'name': 'Transactions API',
            'description': 'Access transaction activity, imported bank events, and related movement history.',
            'overview': 'Use this API to inspect transaction activity for audit, reconciliation, and downstream bookkeeping synchronization.',
            'use_cases': [
                'Pull transaction activity for external client reporting.',
                'Inspect posted movements during reconciliation workflows.',
            ],
            'data_domains': ['transactions', 'payments', 'activity'],
            'data_types': ['historical', 'metadata'],
            'status': 'beta',
            'access_level': 'partner',
            'auth_type': 'oauth2',
            'compliance_notes': 'Transaction history may contain regulated financial activity and should be stored in line with client confidentiality obligations.',
            'rate_limits': {'per_minute': 45, 'per_hour': 1500},
            'keywords': ['transactions', 'payments', 'history'],
            'is_featured': True,
            'featured_rank': 3,
            'categories': ['transactions', 'reporting'],
            'tags': ['historical', 'trades'],
            'version': {
                'version': 'v1',
                'base_path': '/v1/transactions',
                'summary': 'Beta release of transaction retrieval workflows.',
                'status': 'beta',
                'is_default': True,
            },
            'endpoints': [
                {
                    'name': 'List bank transactions',
                    'method': 'GET',
                    'path': '/v1/bank-accounts/{bank_account_id}/transactions',
                    'summary': 'Retrieve imported bank transactions for a linked account.',
                    'description': 'Returns transaction rows and reconciliation status for a specific bank account.',
                    'path_params': [
                        {'name': 'bank_account_id', 'type': 'string', 'required': True, 'description': 'Public bank account identifier.'},
                    ],
                    'query_params': [
                        {'name': 'status', 'type': 'string', 'required': False, 'description': 'Optional reconciliation status filter.'},
                    ],
                    'headers': [
                        {'name': 'Authorization', 'required': True, 'description': 'Bearer token.'},
                        {'name': 'X-Organization-Id', 'required': True, 'description': 'Tenant routing header.'},
                    ],
                    'scopes': ['banking.read'],
                    'request_example': 'curl -X GET "https://api.atonixcorp.com/v1/bank-accounts/bank_123/transactions?status=reconciled" -H "Authorization: Bearer <token>" -H "X-Organization-Id: org_123"',
                    'response_example': '[{"id":"txn_1","external_id":"provider_001","amount":-250.0,"status":"reconciled"}]',
                    'error_responses': [
                        {'status': 404, 'code': 'NOT_FOUND', 'message': 'Resource not found.'},
                    ],
                    'keywords': ['bank transactions', 'reconciliation'],
                    'display_order': 1,
                },
            ],
        },
        {
            'slug': 'risk-limits-api',
            'name': 'Risk & Limits API',
            'description': 'Monitor exposure, risk posture, and operating limits for portfolio and treasury workflows.',
            'overview': 'Use this API to retrieve risk posture and limit-state signals that support operational control and compliance workflows.',
            'use_cases': [
                'Monitor threshold breaches before execution or settlement.',
                'Provide summarized limit data to compliance operations.',
            ],
            'data_domains': ['risk', 'limits', 'exposure'],
            'data_types': ['real-time', 'metadata'],
            'status': 'stable',
            'access_level': 'partner',
            'auth_type': 'oauth2',
            'compliance_notes': 'Use of risk and limit data is subject to internal control, monitoring, and audit obligations.',
            'rate_limits': {'per_minute': 30, 'per_hour': 1000},
            'keywords': ['risk', 'limits', 'exposure'],
            'is_featured': True,
            'featured_rank': 4,
            'categories': ['risk', 'reporting'],
            'tags': ['limits', 'compliance', 'real-time'],
            'version': {
                'version': 'v1',
                'base_path': '/v1/risk',
                'summary': 'Stable risk and operating-limit retrieval services.',
                'status': 'stable',
                'is_default': True,
            },
            'endpoints': [
                {
                    'name': 'Get portfolio risk summary',
                    'method': 'GET',
                    'path': '/v1/risk/summary',
                    'summary': 'Retrieve high-level exposure and limit metrics.',
                    'description': 'Returns summarized risk posture for authorized organizations and configured portfolios.',
                    'headers': [
                        {'name': 'Authorization', 'required': True, 'description': 'Bearer token.'},
                        {'name': 'X-Organization-Id', 'required': True, 'description': 'Tenant routing header.'},
                    ],
                    'scopes': ['risk.read'],
                    'request_example': 'curl -X GET "https://api.atonixcorp.com/v1/risk/summary" -H "Authorization: Bearer <token>" -H "X-Organization-Id: org_123"',
                    'response_example': '{"limit_utilization":0.41,"var_95":125000.0,"breaches":0}',
                    'error_responses': [
                        {'status': 403, 'code': 'FORBIDDEN', 'message': 'You do not have access to this organization.'},
                    ],
                    'keywords': ['risk summary', 'limits', 'var'],
                    'display_order': 1,
                },
            ],
        },
    ]

    for spec in api_specs:
        api, _ = DeveloperAPI.objects.get_or_create(
            slug=spec['slug'],
            defaults={
                'name': spec['name'],
                'description': spec['description'],
                'overview': spec['overview'],
                'use_cases': spec['use_cases'],
                'data_domains': spec['data_domains'],
                'data_types': spec['data_types'],
                'status': spec['status'],
                'access_level': spec['access_level'],
                'auth_type': spec['auth_type'],
                'compliance_notes': spec['compliance_notes'],
                'rate_limits': spec['rate_limits'],
                'keywords': spec['keywords'],
                'is_featured': spec['is_featured'],
                'featured_rank': spec['featured_rank'],
            },
        )
        api.categories.set([category_map[slug] for slug in spec['categories']])
        api.tags.set([tag_map[slug] for slug in spec['tags']])

        version, _ = DeveloperAPIVersion.objects.get_or_create(
            api=api,
            version=spec['version']['version'],
            defaults={
                'base_path': spec['version']['base_path'],
                'summary': spec['version']['summary'],
                'status': spec['version']['status'],
                'is_default': spec['version']['is_default'],
            },
        )

        for endpoint_spec in spec['endpoints']:
            DeveloperAPIEndpoint.objects.get_or_create(
                version=version,
                method=endpoint_spec['method'],
                path=endpoint_spec['path'],
                defaults={
                    'name': endpoint_spec['name'],
                    'summary': endpoint_spec['summary'],
                    'description': endpoint_spec['description'],
                    'path_params': endpoint_spec.get('path_params', []),
                    'query_params': endpoint_spec.get('query_params', []),
                    'headers': endpoint_spec.get('headers', []),
                    'scopes': endpoint_spec.get('scopes', []),
                    'request_example': endpoint_spec.get('request_example', ''),
                    'response_example': endpoint_spec.get('response_example', ''),
                    'error_responses': endpoint_spec.get('error_responses', []),
                    'keywords': endpoint_spec.get('keywords', []),
                    'display_order': endpoint_spec.get('display_order', 0),
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0012_bankaccount_provider_bankaccount_provider_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperAPICategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Developer API Category',
                'verbose_name_plural': 'Developer API Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperAPITag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Developer API Tag',
                'verbose_name_plural': 'Developer API Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('overview', models.TextField()),
                ('use_cases', models.JSONField(blank=True, default=list)),
                ('data_domains', models.JSONField(blank=True, default=list)),
                ('data_types', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('stable', 'Stable'), ('beta', 'Beta'), ('deprecated', 'Deprecated')], default='stable', max_length=20)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('partner', 'Partner'), ('internal', 'Internal')], default='public', max_length=20)),
                ('auth_type', models.CharField(choices=[('api_key', 'API Key'), ('oauth2', 'OAuth 2.0'), ('both', 'API Key and OAuth 2.0')], default='api_key', max_length=20)),
                ('compliance_notes', models.TextField(blank=True)),
                ('rate_limits', models.JSONField(blank=True, default=dict)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_rank', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='apis', to='finances.developerapicategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='apis', to='finances.developerapitag')),
            ],
            options={
                'verbose_name': 'Developer API',
                'verbose_name_plural': 'Developer APIs',
                'ordering': ['featured_rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperAPIVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('base_path', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('stable', 'Stable'), ('beta', 'Beta'), ('deprecated', 'Deprecated')], default='stable', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('release_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='finances.developerapi')),
            ],
            options={
                'verbose_name': 'Developer API Version',
                'verbose_name_plural': 'Developer API Versions',
                'ordering': ['api__name', 'version'],
                'unique_together': {('api', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DeveloperAPIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('path_params', models.JSONField(blank=True, default=list)),
                ('query_params', models.JSONField(blank=True, default=list)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('request_example', models.TextField(blank=True)),
                ('response_example', models.TextField(blank=True)),
                ('error_responses', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='finances.developerapiversion')),
            ],
            options={
                'verbose_name': 'Developer API Endpoint',
                'verbose_name_plural': 'Developer API Endpoints',
                'ordering': ['display_order', 'method', 'path'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperPortalKeyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('intended_use', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('generated', 'Generated'), ('revoked', 'Revoked')], default='submitted', max_length=20)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_portal_key_requests', to='finances.oauthapplication')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_portal_key_requests', to='finances.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_portal_key_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Developer Portal Key Request',
                'verbose_name_plural': 'Developer Portal Key Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_developer_portal_content, migrations.RunPython.noop),
    ]