# Generated by Django 4.2.7 on 2026-07-20 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0040_entity_workspace_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('amendment_type', models.CharField(choices=[('standard', 'Standard'), ('operational', 'Operational'), ('ethical_security', 'Ethical / Security'), ('constitutional', 'Constitutional'), ('sovereignty', 'Sovereignty'), ('emergency', 'Emergency')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('internal_review', 'Internal Review'), ('council_review', 'Council Review'), ('voting', 'Voting'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=20)),
                ('rationale', models.TextField()),
                ('impact_analysis', models.TextField(blank=True)),
                ('ethical_review', models.TextField(blank=True)),
                ('sovereignty_check', models.TextField(blank=True)),
                ('operational_feasibility', models.TextField(blank=True)),
                ('security_implications', models.TextField(blank=True)),
                ('implementation_timeline', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('voting_opens_at', models.DateTimeField(blank=True, null=True)),
                ('voting_closes_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GovernanceVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('abstain', 'Abstain')], max_length=10)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('amendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='finances.governanceamendment')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='GovernancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('edition', models.CharField(default='1.0', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('source_document', models.CharField(blank=True, max_length=500)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_policies', to='finances.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_policies_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['policy_code', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='governanceamendment',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='finances.governancepolicy'),
        ),
        migrations.AddField(
            model_name='governanceamendment',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_amendments_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='governancevote',
            constraint=models.UniqueConstraint(fields=('amendment', 'voter'), name='unique_governance_vote_per_member'),
        ),
        migrations.AddConstraint(
            model_name='governancepolicy',
            constraint=models.UniqueConstraint(fields=('organization', 'policy_code', 'edition'), name='unique_governance_policy_edition'),
        ),
        migrations.AddConstraint(
            model_name='governanceamendment',
            constraint=models.UniqueConstraint(fields=('policy', 'amendment_number'), name='unique_governance_amendment_number'),
        ),
    ]
