# Generated by Django 4.2.7 on 2026-07-20 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0041_governance_policy_registry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperModuleInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.SlugField(max_length=80)),
                ('module_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=40)),
                ('version', models.CharField(default='1.0.0', max_length=40)),
                ('required_tier', models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise'), ('institutional', 'Institutional')], default='basic', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_modules_installed', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_module_installations', to='finances.organization')),
            ],
            options={
                'ordering': ['module_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='developermoduleinstallation',
            constraint=models.UniqueConstraint(fields=('organization', 'module_key'), name='unique_developer_module_installation'),
        ),
    ]
