# Generated by Django 5.2 on 2026-07-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0044_governanceconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDirectoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('organization', 'Organization'), ('office', 'Office'), ('department', 'Department'), ('unit', 'Unit'), ('user', 'User')], max_length=20)),
                ('uid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('dn', models.CharField(max_length=500)),
                ('cn', models.CharField(max_length=255)),
                ('role_code', models.CharField(blank=True, max_length=50)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directory_entries', to='finances.entity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_entries', to='finances.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finances.organizationdirectoryentry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_directory_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['dn']},
        ),
        migrations.AddConstraint(
            model_name='organizationdirectoryentry',
            constraint=models.UniqueConstraint(fields=('organization', 'dn'), name='unique_directory_dn_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='organizationdirectoryentry',
            constraint=models.UniqueConstraint(fields=('organization', 'source_type', 'source_id'), name='unique_directory_source_per_organization'),
        ),
    ]