# Generated by Django 5.2 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0045_organizationdirectoryentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationdirectoryentry',
            name='uid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]