# Generated by Django 5.2 on 2026-07-20

from django.db import migrations, models
from django.db.models.functions.text import Lower


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0046_alter_organizationdirectoryentry_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='registration_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(Lower('name'), name='unique_organization_name_case_insensitive'),
        ),
    ]