# Generated by Django 5.2 on 2026-07-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0047_organization_company_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceCloudExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google_drive', 'Google Drive'), ('onedrive', 'Microsoft OneDrive'), ('aws_s3', 'AWS S3'), ('local_download', 'Local Download')], max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('checksum', models.CharField(max_length=64)),
                ('destination', models.CharField(blank=True, max_length=500)),
                ('remote_reference', models.CharField(blank=True, max_length=500)),
                ('overwrite_confirmed', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_cloud_exports', to='finances.organization')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_cloud_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]