schema_version: v1
document_type: atonixcorp_governance_configuration
generated_at: '2026-07-22T07:46:20.881519+00:00'
organization:
  id: 1
  name: LGX Demo LLC
  registration_number: null
  slug: lgx-demo-llc
  description: ''
  industry: ''
  subscription_tier: enterprise
  primary_country: US
  primary_currency: USD
  settings: {}
entities: []
offices: []
governance_policies: []
workflows: []
ldap_directory:
- uid: null
  dn: o=lgx-demo-llc,dc=atonixcorp
  cn: LGX Demo LLC
  node_type: organization
  role_code: ''
  permissions: []
  source_type: organization
  attributes:
    company_id: 1
    registration_number: null
    subscription_tier: enterprise
  is_active: true
- uid: null
  dn: ou=finance,o=lgx-demo-llc,dc=atonixcorp
  cn: Finance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: finance
  is_active: true
- uid: null
  dn: ou=governance,o=lgx-demo-llc,dc=atonixcorp
  cn: Governance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: governance
  is_active: true
- uid: null
  dn: ou=security,o=lgx-demo-llc,dc=atonixcorp
  cn: Security
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: security
  is_active: true
- uid: null
  dn: ou=technology,o=lgx-demo-llc,dc=atonixcorp
  cn: Technology
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: technology
  is_active: true
- uid: '9316131928'
  dn: uid=9316131928,ou=people,o=lgx-demo-llc,dc=atonixcorp
  cn: v1-owner
  node_type: user
  role_code: FOUNDER
  permissions: []
  source_type: founder
  attributes:
    email: v1-owner@example.com
    company_id: 1
    company_registration_number: null
    is_founder: true
  is_active: true
integrity:
  algorithm: HMAC-SHA256
  key_id: governance-hmac-v1
  checksum: 81d5c6e3a343dd81428ea2c71de48064de55609e88c35bada3d18d2980a26692
  signature: 6afd4825bc20ce2b1feee4a49c3951671d7c761bb2facf5d3b39152a2345e371
