schema_version: v1
document_type: atonixcorp_governance_configuration
generated_at: '2026-07-22T12:27:09.374255+00:00'
organization:
  id: 1
  name: AtonixCorp Holdings
  registration_number: null
  slug: atonixcorp-holdings
  description: ''
  industry: ''
  subscription_tier: enterprise
  primary_country: US
  primary_currency: USD
  settings: {}
entities: []
offices: []
governance_policies: []
workflows: []
ldap_directory:
- uid: null
  dn: o=atonixcorp-holdings,dc=atonixcorp
  cn: AtonixCorp Holdings
  node_type: organization
  role_code: ''
  permissions: []
  source_type: organization
  attributes:
    company_id: 1
    registration_number: null
    subscription_tier: enterprise
  is_active: true
- uid: null
  dn: ou=finance,o=atonixcorp-holdings,dc=atonixcorp
  cn: Finance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: finance
  is_active: true
- uid: null
  dn: ou=governance,o=atonixcorp-holdings,dc=atonixcorp
  cn: Governance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: governance
  is_active: true
- uid: null
  dn: ou=security,o=atonixcorp-holdings,dc=atonixcorp
  cn: Security
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: security
  is_active: true
- uid: null
  dn: ou=technology,o=atonixcorp-holdings,dc=atonixcorp
  cn: Technology
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: technology
  is_active: true
- uid: '6297900408'
  dn: uid=6297900408,ou=people,o=atonixcorp-holdings,dc=atonixcorp
  cn: entity-owner
  node_type: user
  role_code: FOUNDER
  permissions: []
  source_type: founder
  attributes:
    email: entity-owner@example.com
    company_id: 1
    company_registration_number: null
    is_founder: true
  is_active: true
integrity:
  algorithm: HMAC-SHA256
  key_id: governance-hmac-v1
  checksum: 79059073905400f0272d4ce8fab5424e00a1637788153e9c2c1032121852d7cd
  signature: a91a84acfda9ae87bbcb42b0fed5869073881918e69c40f7333e33e660563750
