schema_version: v1
document_type: atonixcorp_governance_configuration
generated_at: '2026-07-20T23:50:49.872447+00:00'
organization:
  id: 1
  name: Secure ID Org
  registration_number: null
  slug: secure-id-org
  description: ''
  industry: ''
  subscription_tier: enterprise
  primary_country: Nigeria
  primary_currency: USD
  settings: {}
entities: []
offices: []
governance_policies: []
workflows: []
ldap_directory:
- uid: null
  dn: o=secure-id-org,dc=atonixcorp
  cn: Secure ID Org
  node_type: organization
  role_code: ''
  permissions: []
  source_type: organization
  attributes:
    company_id: 1
    registration_number: null
    subscription_tier: enterprise
  is_active: true
- uid: null
  dn: ou=finance,o=secure-id-org,dc=atonixcorp
  cn: Finance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: finance
  is_active: true
- uid: null
  dn: ou=governance,o=secure-id-org,dc=atonixcorp
  cn: Governance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: governance
  is_active: true
- uid: null
  dn: ou=security,o=secure-id-org,dc=atonixcorp
  cn: Security
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: security
  is_active: true
- uid: null
  dn: ou=technology,o=secure-id-org,dc=atonixcorp
  cn: Technology
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: technology
  is_active: true
- uid: '7004039461'
  dn: uid=7004039461,ou=people,o=secure-id-org,dc=atonixcorp
  cn: secure-id@example.com
  node_type: user
  role_code: FOUNDER
  permissions: []
  source_type: founder
  attributes:
    email: secure-id@example.com
    company_id: 1
    company_registration_number: null
    is_founder: true
  is_active: true
integrity:
  algorithm: HMAC-SHA256
  key_id: governance-hmac-v1
  checksum: d2ee6efb09a1df083fa5c68e29856f7bcbb87afa2c928497cba7306621459a49
  signature: 465cff447e9e4538fdfb5dc1235e1adbd34fd273c02e525595a4ab91f9544d03
