schema_version: v1
document_type: atonixcorp_governance_configuration
generated_at: '2026-07-22T11:28:32.200354+00:00'
organization:
  id: 1
  name: Workspace Org
  registration_number: null
  slug: workspace-org
  description: ''
  industry: ''
  subscription_tier: enterprise
  primary_country: US
  primary_currency: USD
  settings: {}
entities: []
offices: []
governance_policies: []
workflows: []
ldap_directory:
- uid: null
  dn: o=workspace-org,dc=atonixcorp
  cn: Workspace Org
  node_type: organization
  role_code: ''
  permissions: []
  source_type: organization
  attributes:
    company_id: 1
    registration_number: null
    subscription_tier: enterprise
  is_active: true
- uid: null
  dn: ou=finance,o=workspace-org,dc=atonixcorp
  cn: Finance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: finance
  is_active: true
- uid: null
  dn: ou=governance,o=workspace-org,dc=atonixcorp
  cn: Governance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: governance
  is_active: true
- uid: null
  dn: ou=security,o=workspace-org,dc=atonixcorp
  cn: Security
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: security
  is_active: true
- uid: null
  dn: ou=technology,o=workspace-org,dc=atonixcorp
  cn: Technology
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: technology
  is_active: true
- uid: '6874733251'
  dn: uid=6874733251,ou=people,o=workspace-org,dc=atonixcorp
  cn: workspace-owner
  node_type: user
  role_code: FOUNDER
  permissions: []
  source_type: founder
  attributes:
    email: workspace-owner@example.com
    company_id: 1
    company_registration_number: null
    is_founder: true
  is_active: true
integrity:
  algorithm: HMAC-SHA256
  key_id: governance-hmac-v1
  checksum: e92c89e4da6cc6811feb4b8fa096ed5766458f61d41a7af86f379079a1cfb387
  signature: 126f8fabf973c0a84ddf75d8b03b1ae9becaca66efed3afc6adef35d037e375f
