schema_version: v1
document_type: atonixcorp_governance_configuration
generated_at: '2026-07-22T07:46:29.151916+00:00'
organization:
  id: 1
  name: LGX Demo LLC
  registration_number: null
  slug: lgx-demo-llc
  description: ''
  industry: ''
  subscription_tier: enterprise
  primary_country: US
  primary_currency: USD
  settings: {}
entities: []
offices: []
governance_policies: []
workflows: []
ldap_directory:
- uid: null
  dn: o=lgx-demo-llc,dc=atonixcorp
  cn: LGX Demo LLC
  node_type: organization
  role_code: ''
  permissions: []
  source_type: organization
  attributes:
    company_id: 1
    registration_number: null
    subscription_tier: enterprise
  is_active: true
- uid: null
  dn: ou=finance,o=lgx-demo-llc,dc=atonixcorp
  cn: Finance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: finance
  is_active: true
- uid: null
  dn: ou=governance,o=lgx-demo-llc,dc=atonixcorp
  cn: Governance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: governance
  is_active: true
- uid: null
  dn: ou=security,o=lgx-demo-llc,dc=atonixcorp
  cn: Security
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: security
  is_active: true
- uid: null
  dn: ou=technology,o=lgx-demo-llc,dc=atonixcorp
  cn: Technology
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: technology
  is_active: true
- uid: '6344872710'
  dn: uid=6344872710,ou=people,o=lgx-demo-llc,dc=atonixcorp
  cn: v1-owner
  node_type: user
  role_code: FOUNDER
  permissions: []
  source_type: founder
  attributes:
    email: v1-owner@example.com
    company_id: 1
    company_registration_number: null
    is_founder: true
  is_active: true
integrity:
  algorithm: HMAC-SHA256
  key_id: governance-hmac-v1
  checksum: 6171a4fda7feb1ff04584b94babfa0fd2144a61097e8f200ea6601f90939bb1b
  signature: 650588fea1622184b3a969ce292b0ca1954992a7cade43c9e4e78d571ed0e21b
