schema_version: v1
document_type: atonixcorp_governance_configuration
generated_at: '2026-07-20T23:42:48.294442+00:00'
organization:
  id: 1
  name: Secure ID Org
  registration_number: null
  slug: secure-id-org
  description: ''
  industry: ''
  subscription_tier: enterprise
  primary_country: Nigeria
  primary_currency: USD
  settings: {}
entities: []
offices: []
governance_policies: []
workflows: []
ldap_directory:
- uid: null
  dn: o=secure-id-org,dc=atonixcorp
  cn: Secure ID Org
  node_type: organization
  role_code: ''
  permissions: []
  source_type: organization
  attributes:
    company_id: 1
    registration_number: null
    subscription_tier: enterprise
  is_active: true
- uid: null
  dn: ou=finance,o=secure-id-org,dc=atonixcorp
  cn: Finance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: finance
  is_active: true
- uid: null
  dn: ou=governance,o=secure-id-org,dc=atonixcorp
  cn: Governance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: governance
  is_active: true
- uid: null
  dn: ou=security,o=secure-id-org,dc=atonixcorp
  cn: Security
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: security
  is_active: true
- uid: null
  dn: ou=technology,o=secure-id-org,dc=atonixcorp
  cn: Technology
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: technology
  is_active: true
- uid: '4388208725'
  dn: uid=4388208725,ou=people,o=secure-id-org,dc=atonixcorp
  cn: secure-id@example.com
  node_type: user
  role_code: FOUNDER
  permissions: []
  source_type: founder
  attributes:
    email: secure-id@example.com
    company_id: 1
    company_registration_number: null
    is_founder: true
  is_active: true
integrity:
  algorithm: HMAC-SHA256
  key_id: governance-hmac-v1
  checksum: 70a2915d34e82f329c04064972fba184611e202e2ef8a09b89ef5061a23d9d79
  signature: 894e0695e88ecf03df2d3796b6af0406954f69eb9867ca5e82506a4f8d65d201
