schema_version: v1
document_type: atonixcorp_governance_configuration
generated_at: '2026-07-22T12:27:38.045187+00:00'
organization:
  id: 1
  name: Tamper Recovery Org
  registration_number: null
  slug: tamper-recovery-org
  description: ''
  industry: ''
  subscription_tier: enterprise
  primary_country: US
  primary_currency: USD
  settings: {}
entities: []
offices: []
governance_policies: []
workflows: []
ldap_directory:
- uid: null
  dn: o=tamper-recovery-org,dc=atonixcorp
  cn: Tamper Recovery Org
  node_type: organization
  role_code: ''
  permissions: []
  source_type: organization
  attributes:
    company_id: 1
    registration_number: null
    subscription_tier: enterprise
  is_active: true
- uid: null
  dn: ou=finance,o=tamper-recovery-org,dc=atonixcorp
  cn: Finance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: finance
  is_active: true
- uid: null
  dn: ou=governance,o=tamper-recovery-org,dc=atonixcorp
  cn: Governance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: governance
  is_active: true
- uid: null
  dn: ou=security,o=tamper-recovery-org,dc=atonixcorp
  cn: Security
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: security
  is_active: true
- uid: null
  dn: ou=technology,o=tamper-recovery-org,dc=atonixcorp
  cn: Technology
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: technology
  is_active: true
- uid: '9463731238'
  dn: uid=9463731238,ou=people,o=tamper-recovery-org,dc=atonixcorp
  cn: governance-tamper-owner
  node_type: user
  role_code: FOUNDER
  permissions: []
  source_type: founder
  attributes:
    email: ''
    company_id: 1
    company_registration_number: null
    is_founder: true
  is_active: true
integrity:
  algorithm: HMAC-SHA256
  key_id: governance-hmac-v1
  checksum: 5a1f2b32257ef5d6aaf8bf3105466dc9a06c1a27ceb151ed7a971706f0e065ea
  signature: 602f236e9af96b11c9c1847cda78a397cc53d42f6c6b0568c5dc8f520ce45cd3
