schema_version: v1
document_type: atonixcorp_governance_configuration
generated_at: '2026-07-22T12:27:21.471586+00:00'
organization:
  id: 1
  name: AtonixCorp Holdings
  registration_number: null
  slug: atonixcorp-holdings
  description: ''
  industry: ''
  subscription_tier: enterprise
  primary_country: US
  primary_currency: USD
  settings: {}
entities: []
offices: []
governance_policies: []
workflows: []
ldap_directory:
- uid: null
  dn: o=atonixcorp-holdings,dc=atonixcorp
  cn: AtonixCorp Holdings
  node_type: organization
  role_code: ''
  permissions: []
  source_type: organization
  attributes:
    company_id: 1
    registration_number: null
    subscription_tier: enterprise
  is_active: true
- uid: null
  dn: ou=finance,o=atonixcorp-holdings,dc=atonixcorp
  cn: Finance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: finance
  is_active: true
- uid: null
  dn: ou=governance,o=atonixcorp-holdings,dc=atonixcorp
  cn: Governance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: governance
  is_active: true
- uid: null
  dn: ou=security,o=atonixcorp-holdings,dc=atonixcorp
  cn: Security
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: security
  is_active: true
- uid: null
  dn: ou=technology,o=atonixcorp-holdings,dc=atonixcorp
  cn: Technology
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: technology
  is_active: true
- uid: '2960636260'
  dn: uid=2960636260,ou=people,o=atonixcorp-holdings,dc=atonixcorp
  cn: entity-owner
  node_type: user
  role_code: FOUNDER
  permissions: []
  source_type: founder
  attributes:
    email: entity-owner@example.com
    company_id: 1
    company_registration_number: null
    is_founder: true
  is_active: true
integrity:
  algorithm: HMAC-SHA256
  key_id: governance-hmac-v1
  checksum: d9d35f2f9374d9177451589a2a5d0b598ff4fdf6a048141e4781e6f3fce16120
  signature: 5253cbe7e7257b94756d441b2579c2781bb46105ba00b1b7aebbefdac99ee263
