schema_version: v1
document_type: atonixcorp_governance_configuration
generated_at: '2026-07-22T08:01:52.420074+00:00'
organization:
  id: 1
  name: Identity Code Holdings
  registration_number: null
  slug: identity-code-holdings
  description: ''
  industry: ''
  subscription_tier: enterprise
  primary_country: US
  primary_currency: USD
  settings: {}
entities: []
offices: []
governance_policies: []
workflows: []
ldap_directory:
- uid: null
  dn: o=identity-code-holdings,dc=atonixcorp
  cn: Identity Code Holdings
  node_type: organization
  role_code: ''
  permissions: []
  source_type: organization
  attributes:
    company_id: 1
    registration_number: null
    subscription_tier: enterprise
  is_active: true
- uid: null
  dn: ou=finance,o=identity-code-holdings,dc=atonixcorp
  cn: Finance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: finance
  is_active: true
- uid: null
  dn: ou=governance,o=identity-code-holdings,dc=atonixcorp
  cn: Governance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: governance
  is_active: true
- uid: null
  dn: ou=security,o=identity-code-holdings,dc=atonixcorp
  cn: Security
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: security
  is_active: true
- uid: null
  dn: ou=technology,o=identity-code-holdings,dc=atonixcorp
  cn: Technology
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: technology
  is_active: true
- uid: '5781048542'
  dn: uid=5781048542,ou=people,o=identity-code-holdings,dc=atonixcorp
  cn: code-owner
  node_type: user
  role_code: FOUNDER
  permissions: []
  source_type: founder
  attributes:
    email: code-owner@example.com
    company_id: 1
    company_registration_number: null
    is_founder: true
  is_active: true
integrity:
  algorithm: HMAC-SHA256
  key_id: governance-hmac-v1
  checksum: 6a21041a654331ba4c24a83a4417d80977cf26f380671223a60a31a4fd3a2d3a
  signature: 9a74608d025ef90c888c841dd7d609eda6a48fd74dbe26597d6486b40b3376c4
