schema_version: v1
document_type: atonixcorp_governance_configuration
generated_at: '2026-07-22T12:26:31.536492+00:00'
organization:
  id: 1
  name: LGX Demo LLC
  registration_number: null
  slug: lgx-demo-llc
  description: ''
  industry: ''
  subscription_tier: enterprise
  primary_country: US
  primary_currency: USD
  settings: {}
entities: []
offices: []
governance_policies: []
workflows: []
ldap_directory:
- uid: null
  dn: o=lgx-demo-llc,dc=atonixcorp
  cn: LGX Demo LLC
  node_type: organization
  role_code: ''
  permissions: []
  source_type: organization
  attributes:
    company_id: 1
    registration_number: null
    subscription_tier: enterprise
  is_active: true
- uid: null
  dn: ou=finance,o=lgx-demo-llc,dc=atonixcorp
  cn: Finance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: finance
  is_active: true
- uid: null
  dn: ou=governance,o=lgx-demo-llc,dc=atonixcorp
  cn: Governance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: governance
  is_active: true
- uid: null
  dn: ou=security,o=lgx-demo-llc,dc=atonixcorp
  cn: Security
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: security
  is_active: true
- uid: null
  dn: ou=technology,o=lgx-demo-llc,dc=atonixcorp
  cn: Technology
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: technology
  is_active: true
- uid: '4783403712'
  dn: uid=4783403712,ou=people,o=lgx-demo-llc,dc=atonixcorp
  cn: v1-owner
  node_type: user
  role_code: FOUNDER
  permissions: []
  source_type: founder
  attributes:
    email: v1-owner@example.com
    company_id: 1
    company_registration_number: null
    is_founder: true
  is_active: true
integrity:
  algorithm: HMAC-SHA256
  key_id: governance-hmac-v1
  checksum: ccb611344ede31d8a755289530044f0fa1ae35a6595f2d55d2c236cc559499db
  signature: 65bafbebef48a7247cb60e63e8c8d567cbb81d99263f4892890355f9935d5c3f
