schema_version: v1
document_type: atonixcorp_governance_configuration
generated_at: '2026-07-22T07:46:41.500746+00:00'
organization:
  id: 1
  name: Reporting Org
  registration_number: null
  slug: reporting-org
  description: ''
  industry: ''
  subscription_tier: enterprise
  primary_country: US
  primary_currency: USD
  settings: {}
entities: []
offices: []
governance_policies: []
workflows: []
ldap_directory:
- uid: null
  dn: o=reporting-org,dc=atonixcorp
  cn: Reporting Org
  node_type: organization
  role_code: ''
  permissions: []
  source_type: organization
  attributes:
    company_id: 1
    registration_number: null
    subscription_tier: enterprise
  is_active: true
- uid: null
  dn: ou=finance,o=reporting-org,dc=atonixcorp
  cn: Finance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: finance
  is_active: true
- uid: null
  dn: ou=governance,o=reporting-org,dc=atonixcorp
  cn: Governance
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: governance
  is_active: true
- uid: null
  dn: ou=security,o=reporting-org,dc=atonixcorp
  cn: Security
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: security
  is_active: true
- uid: null
  dn: ou=technology,o=reporting-org,dc=atonixcorp
  cn: Technology
  node_type: office
  role_code: ''
  permissions: []
  source_type: default_office
  attributes:
    office_key: technology
  is_active: true
- uid: '5286338873'
  dn: uid=5286338873,ou=people,o=reporting-org,dc=atonixcorp
  cn: report-owner
  node_type: user
  role_code: FOUNDER
  permissions: []
  source_type: founder
  attributes:
    email: report-owner@example.com
    company_id: 1
    company_registration_number: null
    is_founder: true
  is_active: true
integrity:
  algorithm: HMAC-SHA256
  key_id: governance-hmac-v1
  checksum: 51168d5f30414992a97d26be41e62e5138909a935963dd34414c481aa8a5d2ea
  signature: da451079043ee677f5c812d791c95fcc869c539d2e00ddb191f097d9c5c8abec
