apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atonixcorp
spec:
  tls:
    - hosts:
        - atonixcorp.com
        - www.atonixcorp.com
        - api.atonixcorp.com
      secretName: atonixcorp-production-tls
  rules:
    - host: atonixcorp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 80
    - host: api.atonixcorp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000
