apiVersion: v1
kind: ConfigMap
metadata:
  name: atonixcorp-config
data:
  DJANGO_ALLOWED_HOSTS: "api.atonixcorp.com,atonixcorp.com,www.atonixcorp.com"
  CORS_ALLOWED_ORIGINS: "https://atonixcorp.com,https://www.atonixcorp.com"
  CSRF_TRUSTED_ORIGINS: "https://atonixcorp.com,https://www.atonixcorp.com"
  FRONTEND_BASE_URL: "https://atonixcorp.com"
  APPROVAL_NOTIFICATION_BASE_URL: "https://atonixcorp.com"
  DEPLOYMENT_ENVIRONMENT: production
  APP_VERSION: production
