# Generated by Django 4.2.7 on 2025-12-17 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0003_entitydepartment_entityrole_auditlog_entity_wallet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookkeepingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('bank', 'Bank Account'), ('wallet', 'Wallet'), ('cash', 'Cash')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookkeeping_accounts', to='finances.entity')),
            ],
            options={
                'ordering': ['-is_active', 'type', 'name'],
                'unique_together': {('entity', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BookkeepingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookkeeping_categories', to='finances.entity')),
            ],
            options={
                'verbose_name_plural': 'Bookkeeping Categories',
                'ordering': ['type', 'name'],
                'unique_together': {('entity', 'name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('wallet', 'Wallet'), ('cash', 'Cash'), ('card', 'Card Payment'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('attachment_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finances.bookkeepingaccount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finances.bookkeepingcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finances.entity')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finances.entitystaff')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['entity', 'date'], name='finances_tr_entity__e932b5_idx'), models.Index(fields=['entity', 'type'], name='finances_tr_entity__50374b_idx'), models.Index(fields=['category'], name='finances_tr_categor_b88b3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookkeepingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_transaction', 'Created Transaction'), ('edit_transaction', 'Edited Transaction'), ('delete_transaction', 'Deleted Transaction'), ('create_category', 'Created Category'), ('edit_category', 'Edited Category'), ('delete_category', 'Deleted Category'), ('create_account', 'Created Account'), ('edit_account', 'Edited Account'), ('delete_account', 'Deleted Account')], max_length=50)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookkeeping_audit_logs', to='finances.entity')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity', 'timestamp'], name='finances_bo_entity__76fb2d_idx'), models.Index(fields=['action'], name='finances_bo_action_592f1f_idx')],
            },
        ),
    ]
