# Generated by Django 4.2.7 on 2025-12-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_recurringtransaction_fixedasset_accrualentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tax_type',
            field=models.CharField(choices=[('corporate', 'Corporate Tax'), ('personal', 'Personal Income Tax'), ('vat', 'VAT/Sales Tax')], default='corporate', max_length=20),
        ),
    ]
