# Generated by Django 4.2.7 on 2025-12-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_organization_settings_userprofile_tax_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('tax_rules', models.JSONField(blank=True, default=dict)),
                ('auto_update', models.BooleanField(default=True)),
                ('residency_status', models.CharField(choices=[('detected', 'Detected'), ('confirmed', 'Confirmed'), ('pending', 'Pending')], default='detected', max_length=20)),
                ('compliance_score', models.IntegerField(default=0)),
                ('last_rule_update', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profiles', to='finances.entity')),
            ],
            options={
                'ordering': ['country', '-updated_at'],
                'unique_together': {('entity', 'country')},
            },
        ),
    ]
