# Generated by Django 4.2.7 on 2026-03-15 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0010_webhookendpoint_webhookdelivery_oauthapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apikey',
            name='environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20),
        ),
        migrations.AddField(
            model_name='apikey',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys_revoked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apikey',
            name='scopes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='apikey',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='apikey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_jobs_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oauthapplication',
            name='environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20),
        ),
        migrations.AddField(
            model_name='oauthapplication',
            name='scopes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='oauthapplication',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='oauthapplication',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_applications_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_endpoints_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_endpoints_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='migrationjob',
            name='type',
            field=models.CharField(choices=[('chart_of_accounts', 'Chart of Accounts'), ('customers', 'Customers'), ('vendors', 'Vendors'), ('invoices', 'Invoices'), ('bills', 'Bills'), ('transactions', 'Transactions'), ('opening_balances', 'Opening Balances'), ('historical_financials', 'Historical Financials'), ('bank_statements', 'Bank Statements')], max_length=50),
        ),
    ]
