# Generated by Django 4.2.7 on 2026-03-15 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0011_apikey_created_by_apikey_environment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='provider_account_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='bankingtransaction',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('reconcile', 'Reconcile'), ('bulk_import', 'Bulk Import'), ('replay', 'Replay')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('entity', 'provider', 'provider_account_id')},
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('exact', 'Exact'), ('manual', 'Manual'), ('partial', 'Partial')], default='manual', max_length=20)),
                ('matched_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_match', to='finances.bankingtransaction')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_matches', to='finances.entity')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_matches', to='finances.journalentry')),
                ('matched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_matches_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-matched_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_events', to='finances.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'event_type'], name='finances_sy_organiz_a2a7c1_idx'), models.Index(fields=['created_at'], name='finances_sy_created_786a3d_idx')],
            },
        ),
    ]
