# Generated by Django 4.2.7 on 2026-03-15 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0014_developer_portal_rate_limits_and_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankingintegration',
            name='access_token_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankingintegration',
            name='consent_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankingintegration',
            name='consent_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bankingintegration',
            name='consent_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bankingintegration',
            name='consent_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankingintegration',
            name='consent_scopes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bankingintegration',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banking_integrations', to='finances.entity'),
        ),
        migrations.AddField(
            model_name='bankingintegration',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bankingintegration',
            name='last_webhook_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankingintegration',
            name='provider_code',
            field=models.CharField(default='custom', max_length=50),
        ),
        migrations.AddField(
            model_name='bankingintegration',
            name='refresh_token_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankingintegration',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankingintegration',
            name='token_last_rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankingintegration',
            name='webhook_signing_secret_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bankingintegration',
            name='api_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='BankingCategorizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_pattern', models.CharField(blank=True, max_length=255)),
                ('description_pattern', models.CharField(blank=True, max_length=255)),
                ('match_type', models.CharField(choices=[('exact', 'Exact'), ('contains', 'Contains'), ('regex', 'Regex')], default='contains', max_length=20)),
                ('category_name', models.CharField(max_length=255)),
                ('dashboard_bucket', models.CharField(blank=True, max_length=255)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('learned_from_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banking_rules_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banking_categorization_rules', to='finances.entity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banking_rules_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'merchant_pattern', 'description_pattern'],
            },
        ),
        migrations.CreateModel(
            name='BankingConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('granted', 'Granted'), ('revoked', 'Revoked'), ('failed', 'Failed')], default='requested', max_length=20)),
                ('redirect_uri', models.URLField(blank=True)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('consent_reference', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banking_consent_logs', to='finances.entity')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to='finances.bankingintegration')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banking_consent_logs', to='finances.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banking_consent_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='BankingSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('webhook', 'Webhook')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('partial', 'Partial')], default='queued', max_length=20)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('accounts_processed', models.PositiveIntegerField(default=0)),
                ('transactions_processed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banking_sync_runs', to='finances.entity')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banking_sync_runs', to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='finances.bankingintegration')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='bankingtransaction',
            name='categorization_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bankingtransaction',
            name='categorization_source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bankingtransaction',
            name='dashboard_bucket',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bankingtransaction',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finances.bankingintegration'),
        ),
        migrations.AddField(
            model_name='bankingtransaction',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bankingtransaction',
            name='normalized_category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bankingtransaction',
            name='raw_category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bankingtransaction',
            name='sync_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finances.bankingsyncrun'),
        ),
        migrations.CreateModel(
            name='BankingCategorizationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('rule_engine', 'Rule Engine'), ('provider_hint', 'Provider Hint'), ('keyword', 'Keyword'), ('user_override', 'User Override'), ('ml_feedback', 'ML Feedback'), ('fallback', 'Fallback')], max_length=30)),
                ('raw_category', models.CharField(blank=True, max_length=255)),
                ('assigned_category', models.CharField(max_length=255)),
                ('dashboard_bucket', models.CharField(blank=True, max_length=255)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banking_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorization_decisions', to='finances.bankingtransaction')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banking_categorization_decisions', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banking_categorization_decisions', to='finances.entity')),
                ('matched_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='finances.bankingcategorizationrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bankingcategorizationrule',
            index=models.Index(fields=['entity', 'is_active'], name='finances_ba_entity__9ade7c_idx'),
        ),
        migrations.AddIndex(
            model_name='bankingcategorizationrule',
            index=models.Index(fields=['entity', 'category_name'], name='finances_ba_entity__e87b44_idx'),
        ),
        migrations.AddIndex(
            model_name='bankingconsentlog',
            index=models.Index(fields=['integration', 'requested_at'], name='finances_ba_integrat_6dd3a6_idx'),
        ),
        migrations.AddIndex(
            model_name='bankingsyncrun',
            index=models.Index(fields=['integration', 'started_at'], name='finances_ba_integrat_46bf3a_idx'),
        ),
        migrations.AddIndex(
            model_name='bankingsyncrun',
            index=models.Index(fields=['status'], name='finances_ba_status_18855d_idx'),
        ),
        migrations.AddIndex(
            model_name='bankingcategorizationdecision',
            index=models.Index(fields=['banking_transaction', 'is_current'], name='finances_ba_banking_d210e8_idx'),
        ),
        migrations.AddIndex(
            model_name='bankingcategorizationdecision',
            index=models.Index(fields=['entity', 'assigned_category'], name='finances_ba_entity__c612da_idx'),
        ),
    ]