# Generated by Django 4.2.7 on 2026-04-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0015_banking_consent_and_categorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='entity',
            name='workspace_mode',
            field=models.CharField(choices=[('accounting', 'Accounting'), ('equity', 'Equity'), ('combined', 'Combined'), ('standalone', 'Standalone')], default='accounting', max_length=20),
        ),
    ]
