# Generated by Django 4.2.7 on 2026-04-08 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0016_rename_finances_ba_banking_d210e8_idx_finances_ba_banking_d54ffd_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalApprovalDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('reviewer', 'Reviewer'), ('approver', 'Approver')], max_length=20)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date', 'delegator__last_name'],
            },
        ),
        migrations.CreateModel(
            name='JournalApprovalMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('entry_type', models.CharField(blank=True, choices=[('manual', 'Manual Entry'), ('automated', 'Automated Entry'), ('reversal', 'Reversal Entry'), ('adjusting', 'Adjusting Entry')], max_length=20)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('require_reviewer', models.BooleanField(default=True)),
                ('require_approver', models.BooleanField(default=True)),
                ('allow_self_review', models.BooleanField(default=False)),
                ('allow_self_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['entity', 'minimum_amount', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('stage', models.CharField(choices=[('preparer', 'Preparer'), ('reviewer', 'Reviewer'), ('approver', 'Approver')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['journal_entry', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reversed', 'Reversed'), ('period_locked', 'Blocked By Period Lock'), ('matrix_applied', 'Approval Matrix Applied')], max_length=30)),
                ('stage', models.CharField(blank=True, max_length=20)),
                ('details', models.TextField(blank=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='bankingcategorizationdecision',
            new_name='finances_ba_banking_d54ffd_idx',
            old_name='finances_ba_banking_d210e8_idx',
        ),
        migrations.RenameIndex(
            model_name='bankingcategorizationdecision',
            new_name='finances_ba_entity__a0634e_idx',
            old_name='finances_ba_entity__c612da_idx',
        ),
        migrations.RenameIndex(
            model_name='bankingcategorizationrule',
            new_name='finances_ba_entity__e40d0c_idx',
            old_name='finances_ba_entity__9ade7c_idx',
        ),
        migrations.RenameIndex(
            model_name='bankingcategorizationrule',
            new_name='finances_ba_entity__9cbf3b_idx',
            old_name='finances_ba_entity__e87b44_idx',
        ),
        migrations.RenameIndex(
            model_name='bankingconsentlog',
            new_name='finances_ba_integra_adc958_idx',
            old_name='finances_ba_integrat_6dd3a6_idx',
        ),
        migrations.RenameIndex(
            model_name='bankingsyncrun',
            new_name='finances_ba_integra_afd829_idx',
            old_name='finances_ba_integrat_46bf3a_idx',
        ),
        migrations.RenameIndex(
            model_name='bankingsyncrun',
            new_name='finances_ba_status_e330a0_idx',
            old_name='finances_ba_status_18855d_idx',
        ),
        migrations.RenameIndex(
            model_name='developerportalapilog',
            new_name='finances_de_path_8dd47a_idx',
            old_name='finances_de_path_5d7d54_idx',
        ),
        migrations.RenameIndex(
            model_name='developerportalapilog',
            new_name='finances_de_request_950258_idx',
            old_name='finances_de_reques_d16d69_idx',
        ),
        migrations.RenameIndex(
            model_name='developerportalapilog',
            new_name='finances_de_status__79af03_idx',
            old_name='finances_de_status__4c8062_idx',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='amount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('pending_approval', 'Pending Approval'), ('posted', 'Posted'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bankingconsentlog',
            index=models.Index(fields=['state'], name='finances_ba_state_bcf08e_idx'),
        ),
        migrations.AddField(
            model_name='journalentrychangelog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_change_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentrychangelog',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_change_logs', to='finances.entity'),
        ),
        migrations.AddField(
            model_name='journalentrychangelog',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='finances.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentryapprovalstep',
            name='acted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_approval_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentryapprovalstep',
            name='assigned_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_approval_steps', to='finances.entityrole'),
        ),
        migrations.AddField(
            model_name='journalentryapprovalstep',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_journal_approval_steps', to='finances.entitystaff'),
        ),
        migrations.AddField(
            model_name='journalentryapprovalstep',
            name='delegated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_steps', to='finances.journalapprovaldelegation'),
        ),
        migrations.AddField(
            model_name='journalentryapprovalstep',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='finances.journalentry'),
        ),
        migrations.AddField(
            model_name='journalapprovalmatrix',
            name='approver_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approve_journal_matrices', to='finances.entityrole'),
        ),
        migrations.AddField(
            model_name='journalapprovalmatrix',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_approval_matrices', to='finances.entity'),
        ),
        migrations.AddField(
            model_name='journalapprovalmatrix',
            name='preparer_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_journal_matrices', to='finances.entityrole'),
        ),
        migrations.AddField(
            model_name='journalapprovalmatrix',
            name='reviewer_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_journal_matrices', to='finances.entityrole'),
        ),
        migrations.AddField(
            model_name='journalapprovaldelegation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_delegations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalapprovaldelegation',
            name='delegate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_authority_received', to='finances.entitystaff'),
        ),
        migrations.AddField(
            model_name='journalapprovaldelegation',
            name='delegator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_authority_delegated', to='finances.entitystaff'),
        ),
        migrations.AddField(
            model_name='journalapprovaldelegation',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_approval_delegations', to='finances.entity'),
        ),
        migrations.AddIndex(
            model_name='journalentrychangelog',
            index=models.Index(fields=['journal_entry', 'created_at'], name='finances_jo_journal_65b775_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentrychangelog',
            index=models.Index(fields=['entity', 'action'], name='finances_jo_entity__2a012c_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryapprovalstep',
            index=models.Index(fields=['journal_entry', 'status'], name='finances_jo_journal_cd9207_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryapprovalstep',
            index=models.Index(fields=['assigned_role', 'status'], name='finances_jo_assigne_38c248_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentryapprovalstep',
            unique_together={('journal_entry', 'step_order')},
        ),
        migrations.AddIndex(
            model_name='journalapprovalmatrix',
            index=models.Index(fields=['entity', 'is_active'], name='finances_jo_entity__d4bae2_idx'),
        ),
        migrations.AddIndex(
            model_name='journalapprovalmatrix',
            index=models.Index(fields=['entity', 'entry_type'], name='finances_jo_entity__195ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='journalapprovaldelegation',
            index=models.Index(fields=['entity', 'stage', 'is_active'], name='finances_jo_entity__a36373_idx'),
        ),
        migrations.AddIndex(
            model_name='journalapprovaldelegation',
            index=models.Index(fields=['start_date', 'end_date'], name='finances_jo_start_d_97d6bf_idx'),
        ),
    ]
