# Generated by Django 4.2.7 on 2026-04-08 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0017_journalapprovaldelegation_journalapprovalmatrix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingApprovalDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(blank=True, choices=[('purchase_order', 'Purchase Order'), ('bill', 'Bill'), ('bill_payment', 'Bill Payment'), ('payment', 'Customer Payment')], max_length=30)),
                ('stage', models.CharField(choices=[('preparer', 'Preparer'), ('reviewer', 'Reviewer'), ('approver', 'Approver')], max_length=20)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_delegations_created', to=settings.AUTH_USER_MODEL)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_authority_received', to='finances.entitystaff')),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_authority_delegated', to='finances.entitystaff')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_approval_delegations', to='finances.entity')),
            ],
            options={
                'ordering': ['-start_date', 'delegator__last_name'],
            },
        ),
        migrations.CreateModel(
            name='AccountingApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('purchase_order', 'Purchase Order'), ('bill', 'Bill'), ('bill_payment', 'Bill Payment'), ('payment', 'Customer Payment')], max_length=30)),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_approvals_approved', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_approval_records', to='finances.entity')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_approvals_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='approval_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='approval_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_payments_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_payments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='approval_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approval_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AccountingApprovalMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('object_type', models.CharField(choices=[('purchase_order', 'Purchase Order'), ('bill', 'Bill'), ('bill_payment', 'Bill Payment'), ('payment', 'Customer Payment')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('require_reviewer', models.BooleanField(default=True)),
                ('require_approver', models.BooleanField(default=True)),
                ('allow_self_review', models.BooleanField(default=False)),
                ('allow_self_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approve_accounting_matrices', to='finances.entityrole')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_approval_matrices', to='finances.entity')),
                ('preparer_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_accounting_matrices', to='finances.entityrole')),
                ('reviewer_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_accounting_matrices', to='finances.entityrole')),
            ],
            options={
                'ordering': ['entity', 'object_type', 'minimum_amount', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccountingApprovalChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed'), ('period_locked', 'Blocked By Period Lock'), ('matrix_applied', 'Approval Matrix Applied')], max_length=30)),
                ('stage', models.CharField(blank=True, max_length=20)),
                ('details', models.TextField(blank=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_change_logs', to=settings.AUTH_USER_MODEL)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='finances.accountingapprovalrecord')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_change_logs', to='finances.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountingApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('stage', models.CharField(choices=[('preparer', 'Preparer'), ('reviewer', 'Reviewer'), ('approver', 'Approver')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_approval_actions', to=settings.AUTH_USER_MODEL)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='finances.accountingapprovalrecord')),
                ('assigned_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_approval_steps', to='finances.entityrole')),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_accounting_approval_steps', to='finances.entitystaff')),
                ('delegated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_steps', to='finances.accountingapprovaldelegation')),
            ],
            options={
                'ordering': ['approval', 'step_order'],
                'indexes': [models.Index(fields=['approval', 'status'], name='finances_ac_approva_681cd6_idx'), models.Index(fields=['assigned_role', 'status'], name='finances_ac_assigne_b00ca0_idx')],
                'unique_together': {('approval', 'step_order')},
            },
        ),
        migrations.AddIndex(
            model_name='accountingapprovalrecord',
            index=models.Index(fields=['entity', 'status'], name='finances_ac_entity__76e8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingapprovalrecord',
            index=models.Index(fields=['object_type', 'object_id'], name='finances_ac_object__c524aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountingapprovalrecord',
            unique_together={('object_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='accountingapprovalmatrix',
            index=models.Index(fields=['entity', 'object_type', 'is_active'], name='finances_ac_entity__3372e6_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingapprovaldelegation',
            index=models.Index(fields=['entity', 'object_type', 'stage', 'is_active'], name='finances_ac_entity__a3d7ba_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingapprovaldelegation',
            index=models.Index(fields=['start_date', 'end_date'], name='finances_ac_start_d_3b892a_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingapprovalchangelog',
            index=models.Index(fields=['approval', 'created_at'], name='finances_ac_approva_ce6438_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingapprovalchangelog',
            index=models.Index(fields=['entity', 'action'], name='finances_ac_entity__d36e11_idx'),
        ),
    ]
