# Generated by Django 4.2.7 on 2026-04-08 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0018_accountingapprovaldelegation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntercompanyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('invoice', 'Intercompany Invoice'), ('loan', 'Intercompany Loan'), ('transfer_pricing', 'Transfer Pricing Charge'), ('adjustment', 'Intercompany Adjustment')], max_length=30)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('transaction_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transfer_pricing_markup_percent', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('eliminated', 'Eliminated'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intercompany_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('destination_bill', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_intercompany_transaction', to='finances.bill')),
                ('destination_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercompany_destination_transactions', to='finances.entity')),
                ('destination_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intercompany_destination_transaction', to='finances.journalentry')),
                ('destination_loan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_intercompany_transaction', to='finances.loan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercompany_transactions', to='finances.organization')),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercompany_source_transactions', to='finances.entity')),
                ('source_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_intercompany_transaction', to='finances.invoice')),
                ('source_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intercompany_source_transaction', to='finances.journalentry')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntercompanyEliminationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elimination_type', models.CharField(choices=[('revenue_expense', 'Revenue and Expense Elimination'), ('receivable_payable', 'Receivable and Payable Elimination'), ('loan_balance', 'Loan Balance Elimination'), ('manual_adjustment', 'Manual Adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('adjustment_payload', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consolidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercompany_eliminations', to='finances.consolidation')),
                ('destination_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercompany_eliminations_in', to='finances.entity')),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercompany_eliminations_out', to='finances.entity')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elimination_entries', to='finances.intercompanytransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='intercompanytransaction',
            index=models.Index(fields=['organization', 'transaction_type', 'status'], name='finances_in_organiz_0a66d9_idx'),
        ),
        migrations.AddIndex(
            model_name='intercompanytransaction',
            index=models.Index(fields=['source_entity', 'transaction_date'], name='finances_in_source__acee40_idx'),
        ),
        migrations.AddIndex(
            model_name='intercompanytransaction',
            index=models.Index(fields=['destination_entity', 'transaction_date'], name='finances_in_destina_f908e0_idx'),
        ),
        migrations.AddIndex(
            model_name='intercompanyeliminationentry',
            index=models.Index(fields=['consolidation', 'elimination_type'], name='finances_in_consoli_a79eec_idx'),
        ),
        migrations.AddIndex(
            model_name='intercompanyeliminationentry',
            index=models.Index(fields=['transaction', 'created_at'], name='finances_in_transac_c84231_idx'),
        ),
    ]
