# Generated by Django 4.2.7 on 2026-04-08 17:21

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0019_intercompanytransaction_intercompanyeliminationentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('benefit', 'Benefit'), ('deduction', 'Deduction')], max_length=20)),
                ('calculation_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent_of_base', 'Percent of Base Salary')], default='fixed', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taxable', models.BooleanField(default=True)),
                ('employer_contribution', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_components', to='finances.entity')),
            ],
            options={
                'ordering': ['component_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pay_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('semimonthly', 'Semi-Monthly'), ('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('processed', 'Processed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('gross_pay_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('employee_benefits_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('employer_benefits_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deductions_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_withholding_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('employer_tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_pay_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statutory_summary', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='finances.entity')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to='finances.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='finances.organization')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('employee_benefits_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('employer_benefits_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deductions_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taxable_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_withholding', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('employer_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('leave_accrued_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('leave_used_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('leave_balance_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bank_payment_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('paid', 'Paid'), ('void', 'Void')], default='generated', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['staff_member__last_name', 'staff_member__first_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffPayrollProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('semimonthly', 'Semi-Monthly'), ('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('salary_basis', models.CharField(choices=[('annual', 'Annual Salary'), ('monthly', 'Monthly Salary')], default='annual', max_length=20)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('standard_hours_per_period', models.DecimalField(decimal_places=2, default=Decimal('160.00'), max_digits=8)),
                ('income_tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('employee_tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('employer_tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('default_bank_account_name', models.CharField(blank=True, max_length=255)),
                ('default_bank_account_number', models.CharField(blank=True, max_length=100)),
                ('default_bank_routing_number', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('tax_identifier', models.CharField(blank=True, max_length=100)),
                ('statutory_jurisdiction', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_payroll_profiles', to='finances.entity')),
                ('staff_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_profile', to='finances.entitystaff')),
            ],
            options={
                'ordering': ['staff_member__last_name', 'staff_member__first_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffPayrollComponentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_override', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_start', models.DateField(blank=True, null=True)),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='finances.payrollcomponent')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_component_assignments', to='finances.entitystaff')),
            ],
            options={
                'ordering': ['component__component_type', 'component__name'],
            },
        ),
        migrations.CreateModel(
            name='PayslipLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('earning', 'Earning'), ('benefit', 'Benefit'), ('deduction', 'Deduction'), ('withholding', 'Withholding'), ('employer_tax', 'Employer Tax'), ('leave', 'Leave')], max_length=20)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taxable', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finances.payslip')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='payslip',
            name='payroll_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='finances.staffpayrollprofile'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payroll_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='finances.payrollrun'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='finances.entitystaff'),
        ),
        migrations.CreateModel(
            name='PayrollStatutoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('withholding_return', 'Withholding Return'), ('social_contribution', 'Social Contribution Report'), ('payroll_register', 'Payroll Register')], max_length=30)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('filed', 'Filed'), ('submitted', 'Submitted')], default='generated', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('report_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_reports', to='finances.payrollrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollBankPaymentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('sepa', 'SEPA'), ('aba', 'ABA')], default='csv', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('exported', 'Exported')], default='generated', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_payment_file', to='finances.payrollrun')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('accrual_hours_per_run', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_balance_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carryover_limit_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_paid_leave', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='finances.entity')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hours_requested', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed In Payroll')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='finances.entity')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='finances.leavetype')),
                ('payroll_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_leave_requests', to='finances.payrollrun')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='finances.entitystaff')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('accrued_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('used_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='finances.leavetype')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='finances.entitystaff')),
            ],
            options={
                'ordering': ['staff_member__last_name', 'leave_type__name'],
            },
        ),
        migrations.AddIndex(
            model_name='staffpayrollprofile',
            index=models.Index(fields=['entity', 'is_active'], name='finances_st_entity__26cfbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffpayrollcomponentassignment',
            unique_together={('staff_member', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('payroll_run', 'staff_member')},
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['entity', 'status'], name='finances_pa_entity__026d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['organization', 'payment_date'], name='finances_pa_organiz_a07d59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollcomponent',
            unique_together={('entity', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('entity', 'code')},
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['entity', 'status'], name='finances_le_entity__53e428_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['staff_member', 'start_date'], name='finances_le_staff_m_fadda9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('staff_member', 'leave_type')},
        ),
    ]
