# Generated by Django 4.2.7 on 2026-04-08 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0020_payrollcomponent_payrollrun_payslip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='approval_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='requested_bank_file_format',
            field=models.CharField(choices=[('csv', 'CSV'), ('sepa', 'SEPA'), ('aba', 'ABA'), ('bacs', 'BACS')], default='csv', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountingapprovaldelegation',
            name='object_type',
            field=models.CharField(blank=True, choices=[('purchase_order', 'Purchase Order'), ('bill', 'Bill'), ('bill_payment', 'Bill Payment'), ('payment', 'Customer Payment'), ('payroll_run', 'Payroll Run')], max_length=30),
        ),
        migrations.AlterField(
            model_name='accountingapprovalmatrix',
            name='object_type',
            field=models.CharField(choices=[('purchase_order', 'Purchase Order'), ('bill', 'Bill'), ('bill_payment', 'Bill Payment'), ('payment', 'Customer Payment'), ('payroll_run', 'Payroll Run')], max_length=30),
        ),
        migrations.AlterField(
            model_name='accountingapprovalrecord',
            name='object_type',
            field=models.CharField(choices=[('purchase_order', 'Purchase Order'), ('bill', 'Bill'), ('bill_payment', 'Bill Payment'), ('payment', 'Customer Payment'), ('payroll_run', 'Payroll Run')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payrollbankpaymentfile',
            name='file_format',
            field=models.CharField(choices=[('csv', 'CSV'), ('sepa', 'SEPA'), ('aba', 'ABA'), ('bacs', 'BACS')], default='csv', max_length=20),
        ),
    ]
