# Generated by Django 4.2.7 on 2026-04-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0021_payrollrun_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='requested_bank_export_variant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='requested_bank_institution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staffpayrollprofile',
            name='default_bank_iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='staffpayrollprofile',
            name='default_bank_sort_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staffpayrollprofile',
            name='default_bank_swift_code',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
