# Generated by Django 4.2.7 on 2026-04-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0022_payrollrun_requested_bank_export_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollBankOriginatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originator_name', models.CharField(max_length=255)),
                ('originator_identifier', models.CharField(blank=True, max_length=100)),
                ('originating_bank_name', models.CharField(blank=True, max_length=255)),
                ('debit_account_name', models.CharField(blank=True, max_length=255)),
                ('debit_account_number', models.CharField(blank=True, max_length=100)),
                ('debit_routing_number', models.CharField(blank=True, max_length=50)),
                ('debit_iban', models.CharField(blank=True, max_length=34)),
                ('debit_swift_code', models.CharField(blank=True, max_length=11)),
                ('debit_sort_code', models.CharField(blank=True, max_length=20)),
                ('company_entry_description', models.CharField(blank=True, max_length=20)),
                ('company_discretionary_data', models.CharField(blank=True, max_length=20)),
                ('initiating_party_name', models.CharField(blank=True, max_length=255)),
                ('initiating_party_identifier', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_bank_originator_profile', to='finances.entity')),
            ],
            options={
                'ordering': ['entity__name'],
            },
        ),
    ]
