# Generated by Django 4.2.7 on 2026-04-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0035_tax_governance_risk_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='service_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
