# Generated by Django 4.2.7 on 2026-04-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0036_vendor_service_description_vendor_website_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="entity",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="permission",
            name="code",
            field=models.CharField(
                choices=[
                    ("view_org_overview", "View Organization Overview"),
                    ("manage_org_settings", "Manage Organization Settings"),
                    ("manage_billing", "Manage Billing"),
                    ("view_entities", "View Entities"),
                    ("create_entity", "Create Entity"),
                    ("edit_entity", "Edit Entity"),
                    ("delete_entity", "Delete Entity"),
                    ("view_tax_compliance", "View Tax Compliance"),
                    ("edit_tax_compliance", "Edit Tax Compliance"),
                    ("manage_tax_regimes", "Manage Tax Regimes"),
                    ("view_tax_audit_logs", "View Tax Audit Logs"),
                    ("submit_tax_filings", "Submit Tax Filings"),
                    ("run_tax_calculations", "Run Tax Calculations"),
                    ("edit_tax_registrations", "Edit Tax Registration Numbers"),
                    ("export_tax_reports", "Export Tax Reports"),
                    ("view_cashflow", "View Cashflow"),
                    ("edit_cashflow", "Edit Cashflow"),
                    ("view_risk_exposure", "View Risk Exposure"),
                    ("edit_risk_exposure", "Edit Risk Exposure"),
                    ("view_reports", "View Reports"),
                    ("generate_reports", "Generate Reports"),
                    ("export_reports", "Export Reports"),
                    ("view_team", "View Team Members"),
                    ("manage_team", "Manage Team Members"),
                    ("assign_roles", "Assign Roles"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(
                choices=[
                    ("ORG_OWNER", "Organization Owner"),
                    ("CFO", "Chief Financial Officer"),
                    ("FINANCE_ANALYST", "Finance Analyst"),
                    ("VIEWER", "Viewer"),
                    ("EXTERNAL_ADVISOR", "External Advisor"),
                    ("COMPLIANCE_OFFICER", "Compliance Officer"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
