# Generated by Django 4.2.7 on 2026-07-20 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finances", "0042_developer_module_marketplace"),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernanceCommissionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("organization_activity", "Organization Activity"),
                            ("financial_transaction", "Financial Transaction"),
                            ("infrastructure_deployment", "Infrastructure Deployment"),
                            ("compliance_enforcement", "Compliance Enforcement"),
                            ("governance_approval", "Governance Approval"),
                        ],
                        max_length=40,
                    ),
                ),
                ("rate_percent", models.DecimalField(decimal_places=4, max_digits=7)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="governance_commission_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="governance_commission_plans",
                        to="finances.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["role_code", "trigger_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceCommissionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_reference", models.CharField(max_length=100)),
                ("source_description", models.CharField(blank=True, max_length=255)),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accrued", "Accrued"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                        ],
                        default="accrued",
                        max_length=20,
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "calculated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="governance_commission_entries_calculated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="finances.governancecommissionplan",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="governance_commission_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-calculated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="governancecommissionplan",
            constraint=models.UniqueConstraint(
                fields=("organization", "role_code", "trigger_type", "name"),
                name="unique_governance_commission_plan",
            ),
        ),
        migrations.AddConstraint(
            model_name="governancecommissionentry",
            constraint=models.UniqueConstraint(
                fields=("plan", "source_reference", "recipient"),
                name="unique_governance_commission_source",
            ),
        ),
    ]
