# Generated by Django 5.2 on 2026-07-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0043_governance_commission_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.CharField(default='v1', max_length=20)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('configuration_file', models.FileField(upload_to='governance_configurations/')),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='governance_configuration', to='finances.organization')),
            ],
        ),
    ]