# Generated by Django 5.2.16 on 2026-07-20 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0048_governancecloudexport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('ORG_OWNER', 'Organization Owner'), ('CFO', 'Chief Financial Officer'), ('FINANCE_ANALYST', 'Finance Analyst'), ('VIEWER', 'Viewer'), ('EXTERNAL_ADVISOR', 'External Advisor'), ('COMPLIANCE_OFFICER', 'Compliance Officer'), ('FOUNDER', 'Founder'), ('CEO', 'Chief Executive Officer'), ('CTO', 'Chief Technology Officer'), ('CSO', 'Chief Security Officer'), ('BOARD', 'Board Member'), ('DEPARTMENT_HEAD', 'Department Head'), ('UNIT_MEMBER', 'Unit Member')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='OrganizationEmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_part', models.CharField(max_length=64)),
                ('address', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to='finances.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationEmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.CharField(choices=[('governance', 'Governance Notice'), ('operational', 'Operational Notice'), ('marketing', 'Marketing Campaign')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField()),
                ('recipients', models.JSONField(default=list)),
                ('consent_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='finances.organization')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='finances.organizationemailaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationEmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('event_type', models.CharField(default='campaign', max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='finances.organizationemailcampaign')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_deliveries', to='finances.organization')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='finances.organizationemailaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationEmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('billing_reference', models.CharField(blank=True, max_length=120)),
                ('monthly_send_limit', models.PositiveIntegerField(default=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_subscription', to='finances.organization')),
            ],
            options={
                'ordering': ['organization__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='organizationemailaccount',
            constraint=models.UniqueConstraint(fields=('organization', 'local_part'), name='unique_organization_email_local_part'),
        ),
        migrations.AddIndex(
            model_name='organizationemaildelivery',
            index=models.Index(fields=['organization', 'created_at'], name='finances_or_organiz_873a64_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationemaildelivery',
            index=models.Index(fields=['campaign', 'status'], name='finances_or_campaig_1cf1fd_idx'),
        ),
    ]
