# Generated by Django 5.2.16 on 2026-07-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0050_email_and_identity_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="invite_code_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="teammember",
            name="invite_code_issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
