# Generated by Django 5.2.16 on 2026-07-22

from django.db import migrations, models
from django.utils import timezone


def backfill_public_identity_codes(apps, schema_editor):
    UserProfile = apps.get_model('finances', 'UserProfile')
    Organization = apps.get_model('finances', 'Organization')
    EntityDepartment = apps.get_model('finances', 'EntityDepartment')
    IdentityCodeSequence = apps.get_model('finances', 'IdentityCodeSequence')
    year = timezone.now().year

    def next_code(code_type):
        sequence, _ = IdentityCodeSequence.objects.get_or_create(
            code_type=code_type,
            year=year,
            defaults={'last_value': 0},
        )
        sequence.last_value += 1
        sequence.save(update_fields=['last_value'])
        return f'AC-{code_type}-{year}-{sequence.last_value:03d}'

    for profile in UserProfile.objects.filter(identity_code__isnull=True).order_by('pk'):
        profile.identity_code = next_code('USR')
        profile.save(update_fields=['identity_code'])

    for organization in Organization.objects.filter(enterprise_code__isnull=True).order_by('pk'):
        organization.enterprise_code = next_code('ENT')
        organization.save(update_fields=['enterprise_code'])

    for department in EntityDepartment.objects.filter(department_code__isnull=True).order_by('pk'):
        department.department_code = next_code('DEP')
        department.save(update_fields=['department_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0051_teammember_invite_code_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(max_length=3)),
                ('year', models.PositiveIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code_type', 'year'), name='unique_identity_code_sequence')],
            },
        ),
        migrations.AddField(
            model_name='entitydepartment',
            name='department_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='enterprise_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identity_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='platform_role',
            field=models.CharField(choices=[('super_user', 'Super User'), ('admin', 'Admin'), ('member', 'Member'), ('employee', 'Employee')], default='member', max_length=20),
        ),
        migrations.RunPython(backfill_public_identity_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='entitydepartment',
            name='department_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='enterprise_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='identity_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, unique=True),
        ),
    ]