# Generated by Django 5.2.16 on 2026-07-22

import re

from django.db import migrations, models
from django.utils import timezone


def backfill_identity_details(apps, schema_editor):
    UserProfile = apps.get_model('finances', 'UserProfile')
    Organization = apps.get_model('finances', 'Organization')
    TeamMember = apps.get_model('finances', 'TeamMember')
    IdentityCodeSequence = apps.get_model('finances', 'IdentityCodeSequence')
    EnterpriseInvitationSequence = apps.get_model('finances', 'EnterpriseInvitationSequence')

    def next_value(code_type, year):
        sequence, _ = IdentityCodeSequence.objects.get_or_create(
            code_type=code_type,
            year=year,
            defaults={'last_value': 0},
        )
        sequence.last_value += 1
        sequence.save(update_fields=['last_value'])
        return sequence.last_value

    for profile in UserProfile.objects.filter(public_user_id__isnull=True).select_related('user').order_by('pk'):
        created_date = timezone.localtime(profile.created_at).date() if profile.created_at else timezone.localdate()
        initials = re.sub(r'[^A-Z0-9]', '', f'{profile.user.first_name[:3]}{profile.user.last_name[:3]}'.upper())
        initials = (initials or 'USR')[:6]
        sequence = next_value('UID', created_date.year)
        profile.public_user_id = f'{initials}-{created_date:%d%m%y}-{created_date.year}-{sequence:03d}'
        profile.save(update_fields=['public_user_id'])

    for organization in Organization.objects.filter(enterprise_username__isnull=True).order_by('pk'):
        base_username = re.sub(r'[^a-z0-9]', '', organization.name.lower())[:140] or 'enterprise'
        candidate = f'{base_username}{organization.created_at:%Y}'
        suffix = 1
        while Organization.objects.exclude(pk=organization.pk).filter(enterprise_username__iexact=candidate).exists():
            suffix += 1
            candidate = f'{base_username}{suffix:03d}'
        organization.enterprise_username = candidate
        organization.save(update_fields=['enterprise_username'])

    counters = {}
    for member in TeamMember.objects.filter(invite_code_hash__gt='').select_related('organization').order_by('organization_id', 'pk'):
        counter = counters.get(member.organization_id, 0) + 1
        counters[member.organization_id] = counter
        member.invitation_reference = f'INV-{member.organization.enterprise_code}-{counter:02d}'
        member.save(update_fields=['invitation_reference'])

    for organization_id, last_value in counters.items():
        EnterpriseInvitationSequence.objects.update_or_create(
            organization_id=organization_id,
            defaults={'last_value': last_value},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0052_public_identity_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseInvitationSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('organization', models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='invitation_sequence', to='finances.organization')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='enterprise_username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='invitation_reference',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_user_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.RunPython(backfill_identity_details, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='organization',
            name='enterprise_username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='invitation_reference',
            field=models.CharField(blank=True, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='public_user_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40, unique=True),
        ),
    ]