# Generated by Django 5.2.16 on 2026-07-22

import re

from django.db import migrations


CODE_PATTERN = re.compile(r'^(?:AC-)?(ENT|DEP|WSP)-(\d{4})-(\d+)$')


def normalize_public_code_sequences(apps, schema_editor):
    Organization = apps.get_model('finances', 'Organization')
    EntityDepartment = apps.get_model('finances', 'EntityDepartment')
    TeamMember = apps.get_model('finances', 'TeamMember')
    Workspace = apps.get_model('workspaces', 'Workspace')

    enterprise_codes = {}
    for organization in Organization.objects.exclude(enterprise_code='').order_by('pk'):
        match = CODE_PATTERN.match(organization.enterprise_code or '')
        if not match:
            continue
        normalized_code = f'AC-{match.group(1)}-{match.group(2)}-{int(match.group(3)):03d}'
        if normalized_code != organization.enterprise_code:
            enterprise_codes[organization.enterprise_code] = normalized_code
            organization.enterprise_code = normalized_code
            organization.save(update_fields=['enterprise_code'])

    for department in EntityDepartment.objects.exclude(department_code='').order_by('pk'):
        match = CODE_PATTERN.match(department.department_code or '')
        if match:
            department.department_code = f'AC-{match.group(1)}-{match.group(2)}-{int(match.group(3)):03d}'
            department.save(update_fields=['department_code'])

    for workspace in Workspace.objects.exclude(workspace_code='').order_by('pk'):
        match = CODE_PATTERN.match(workspace.workspace_code or '')
        if match:
            workspace.workspace_code = f'AC-{match.group(1)}-{match.group(2)}-{int(match.group(3)):03d}'
            workspace.save(update_fields=['workspace_code'])

    for member in TeamMember.objects.exclude(invitation_reference='').order_by('pk'):
        for old_code, new_code in enterprise_codes.items():
            if member.invitation_reference.startswith(f'INV-{old_code}-'):
                member.invitation_reference = member.invitation_reference.replace(old_code, new_code, 1)
                member.save(update_fields=['invitation_reference'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0053_user_identity_and_invitation_references'),
        ('workspaces', '0007_workspace_workspace_code'),
    ]

    operations = [
        migrations.RunPython(normalize_public_code_sequences, migrations.RunPython.noop),
    ]