# Generated by Django 5.2.16 on 2026-07-22

from django.db import migrations


def add_ac_prefix_to_public_codes(apps, schema_editor):
    UserProfile = apps.get_model('finances', 'UserProfile')
    Organization = apps.get_model('finances', 'Organization')
    EntityDepartment = apps.get_model('finances', 'EntityDepartment')
    TeamMember = apps.get_model('finances', 'TeamMember')
    Workspace = apps.get_model('workspaces', 'Workspace')

    enterprise_code_map = {}

    for profile in UserProfile.objects.exclude(identity_code='').order_by('pk'):
        if not profile.identity_code.startswith('AC-'):
            profile.identity_code = f'AC-{profile.identity_code}'
            profile.save(update_fields=['identity_code'])

        if profile.public_user_id and not profile.public_user_id.startswith('AC-'):
            profile.public_user_id = f'AC-{profile.public_user_id}'
            profile.save(update_fields=['public_user_id'])

    for organization in Organization.objects.exclude(enterprise_code='').order_by('pk'):
        old_code = organization.enterprise_code
        if old_code.startswith('AC-'):
            continue
        new_code = f'AC-{old_code}'
        enterprise_code_map[old_code] = new_code
        organization.enterprise_code = new_code
        organization.save(update_fields=['enterprise_code'])

    for department in EntityDepartment.objects.exclude(department_code='').order_by('pk'):
        if not department.department_code.startswith('AC-'):
            department.department_code = f'AC-{department.department_code}'
            department.save(update_fields=['department_code'])

    for workspace in Workspace.objects.exclude(workspace_code='').order_by('pk'):
        if not workspace.workspace_code.startswith('AC-'):
            workspace.workspace_code = f'AC-{workspace.workspace_code}'
            workspace.save(update_fields=['workspace_code'])

    for member in TeamMember.objects.exclude(invitation_reference='').order_by('pk'):
        for old_code, new_code in enterprise_code_map.items():
            if member.invitation_reference.startswith(f'INV-{old_code}-'):
                member.invitation_reference = member.invitation_reference.replace(old_code, new_code, 1)
                member.save(update_fields=['invitation_reference'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0055_dashboard_access_grants'),
        ('workspaces', '0007_workspace_workspace_code'),
    ]

    operations = [
        migrations.RunPython(add_ac_prefix_to_public_codes, migrations.RunPython.noop),
    ]
