from django.urls import path

from .v1_views import (
    AccountsView,
    APIKeysView,
    APIKeyRevokeView,
    APIKeyRotateView,
    AuthTokenView,
    BalanceSheetView,
    BillPaymentsView,
    BillsView,
    BankAccountsView,
    BankAccountTransactionsView,
    CashFlowView,
    CustomersView,
    InvoicePaymentsView,
    InvoicesView,
    JournalEntriesView,
    MigrationBillsView,
    MigrationBankStatementsView,
    MigrationChartOfAccountsView,
    MigrationCustomersView,
    MigrationHistoricalFinancialsView,
    MigrationInvoicesView,
    MigrationJobsView,
    MigrationJobDetailView,
    MigrationOpeningBalancesView,
    MigrationTransactionsView,
    MigrationVendorsView,
    OpenAPISchemaView,
    OrganizationsView,
    PermissionsView,
    ProfitAndLossView,
    ReconciliationMatchesView,
    RedocView,
    RolesView,
    SwaggerUIView,
    SystemEventsView,
    TeamMemberDeactivateView,
    TeamMemberInviteView,
    TeamMembersView,
    TrialBalanceView,
    VendorsView,
    WebhookDeliveriesView,
    WebhookEndpointsView,
    WebhookEventReplayView,
)


urlpatterns = [
    path('openapi.yaml', OpenAPISchemaView.as_view(), name='v1-openapi-schema'),
    path('docs', RedocView.as_view(), name='v1-redoc'),
    path('swagger', SwaggerUIView.as_view(), name='v1-swagger'),
    path('auth/token', AuthTokenView.as_view(), name='v1-auth-token'),
    path('api-keys', APIKeysView.as_view(), name='v1-api-keys'),
    path('api-keys/<str:key_id>/rotate', APIKeyRotateView.as_view(), name='v1-api-key-rotate'),
    path('api-keys/<str:key_id>/revoke', APIKeyRevokeView.as_view(), name='v1-api-key-revoke'),
    path('organizations', OrganizationsView.as_view(), name='v1-organizations'),
    path('roles', RolesView.as_view(), name='v1-roles'),
    path('permissions', PermissionsView.as_view(), name='v1-permissions'),
    path('team-members', TeamMembersView.as_view(), name='v1-team-members'),
    path('team-members/invitations', TeamMemberInviteView.as_view(), name='v1-team-member-invitations'),
    path('team-members/<str:team_member_id>/deactivate', TeamMemberDeactivateView.as_view(), name='v1-team-member-deactivate'),
    path('migration/jobs', MigrationJobsView.as_view(), name='v1-migration-jobs'),
    path('migration/jobs/<str:job_id>', MigrationJobDetailView.as_view(), name='v1-migration-job-detail'),
    path('migration/bank-statements', MigrationBankStatementsView.as_view(), name='v1-migration-bank-statements'),
    path('migration/chart-of-accounts', MigrationChartOfAccountsView.as_view(), name='v1-migration-chart-of-accounts'),
    path('migration/customers', MigrationCustomersView.as_view(), name='v1-migration-customers'),
    path('migration/historical-financials', MigrationHistoricalFinancialsView.as_view(), name='v1-migration-historical-financials'),
    path('migration/vendors', MigrationVendorsView.as_view(), name='v1-migration-vendors'),
    path('migration/invoices', MigrationInvoicesView.as_view(), name='v1-migration-invoices'),
    path('migration/bills', MigrationBillsView.as_view(), name='v1-migration-bills'),
    path('migration/transactions', MigrationTransactionsView.as_view(), name='v1-migration-transactions'),
    path('migration/opening-balances', MigrationOpeningBalancesView.as_view(), name='v1-migration-opening-balances'),
    path('accounts', AccountsView.as_view(), name='v1-accounts'),
    path('customers', CustomersView.as_view(), name='v1-customers'),
    path('vendors', VendorsView.as_view(), name='v1-vendors'),
    path('bills', BillsView.as_view(), name='v1-bills'),
    path('bills/<str:bill_id>/payments', BillPaymentsView.as_view(), name='v1-bill-payments'),
    path('ledger/journal-entries', JournalEntriesView.as_view(), name='v1-journal-entries'),
    path('invoices', InvoicesView.as_view(), name='v1-invoices'),
    path('invoices/<str:invoice_id>/payments', InvoicePaymentsView.as_view(), name='v1-invoice-payments'),
    path('bank-accounts', BankAccountsView.as_view(), name='v1-bank-accounts'),
    path('bank-accounts/<str:bank_account_id>/transactions', BankAccountTransactionsView.as_view(), name='v1-bank-account-transactions'),
    path('reconciliation/matches', ReconciliationMatchesView.as_view(), name='v1-reconciliation-matches'),
    path('reports/trial-balance', TrialBalanceView.as_view(), name='v1-trial-balance'),
    path('reports/profit-and-loss', ProfitAndLossView.as_view(), name='v1-profit-and-loss'),
    path('reports/balance-sheet', BalanceSheetView.as_view(), name='v1-balance-sheet'),
    path('reports/cash-flow', CashFlowView.as_view(), name='v1-cash-flow'),
    path('events', SystemEventsView.as_view(), name='v1-system-events'),
    path('webhooks/endpoints', WebhookEndpointsView.as_view(), name='v1-webhook-endpoints'),
    path('webhooks/deliveries', WebhookDeliveriesView.as_view(), name='v1-webhook-deliveries'),
    path('webhooks/events/<str:event_id>/replay', WebhookEventReplayView.as_view(), name='v1-webhook-event-replay'),
]
