apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - rbac.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-hpa.yaml
  - backend-pdb.yaml
  - banking-sync-deployment.yaml
  - approval-digest-deployment.yaml
  - app-deployment.yaml
  - app-service.yaml
  - app-hpa.yaml
  - app-pdb.yaml
  - ingress.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/part-of: atonixcorp
  app.kubernetes.io/managed-by: kubectl
