apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ledgora-prod

resources:
  - ../../base
  - namespace.yaml

patchesStrategicMerge:
  - patch-config.yaml
  - patch-backend.yaml
  - patch-app.yaml
  - patch-ingress.yaml

images:
  - name: ledgora/backend
    newName: registry.example.com/ledgora/backend
    newTag: prod
  - name: ledgora/app
    newName: registry.example.com/ledgora/app
    newTag: prod