apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atonixcorp-prod

resources:
  - ../../base
  - namespace.yaml

patchesStrategicMerge:
  - patch-config.yaml
  - patch-backend.yaml
  - patch-app.yaml
  - patch-ingress.yaml

images:
  - name: atonixcorp/backend
    newName: registry.example.com/atonixcorp/backend
    newTag: prod
  - name: atonixcorp/app
    newName: registry.example.com/atonixcorp/app
    newTag: prod