apiVersion: v1
kind: ConfigMap
metadata:
  name: atonixcorp-config
data:
  DJANGO_ALLOWED_HOSTS: "api.dev.atonixcorp.com,localhost"
  CORS_ALLOWED_ORIGINS: "https://app.dev.atonixcorp.com"
  CSRF_TRUSTED_ORIGINS: "https://app.dev.atonixcorp.com"
  DEPLOYMENT_ENVIRONMENT: "dev"
  APP_VERSION: "dev"